❗Note: I ran out of RAM due to One-Hot encoding so I am using this new notebook to transfer the strictly necessary commands and functions for this milestone ❗

# Exploring Netflix's TV Shows and Movies based on production details

Madeleinne Tan (ID 1221366627)

Goal: I was looking up datasets on Kaggle and I came across this: https://www.kaggle.com/datasets/shivamb/netflix-shows

I have always been interested in Netflix movies and TV shows, specifically with the following questions:
- What kinds of movies/shows are added and kept on Netflix?
- How often are movies/shows added to Netflix?
- What kinds of movies do Netflix recommend? Can we use clustering to look at the movies/shows Netflix have as of the creation of this dataset?

I'm especially interested in the last question. I would, eventually, like to do clustering to explore how the movies (or shows) are related on Netflix and how they keep items to attract new subscribers. Unfortunately, there are no datapoints about viewerships so it's hard to tell how subscribers react to movies.

List of features:
1. show_id : the unique ID for every movie / tv show
2. type : "movie" or "tv show"
3. title : title of the movie
4. director : director of the movie
5. cast : cast of the movie
6. country : where the movie or show was produced
7. date_added : the date it was added on Netflix
8. release_year : the actual release year of the movie or tv show.
9. rating : the TV rating of the movie or TV show (e.g. PG, TV-MA...)
10. duration : the total duration, in minutes (movies) or number of seasons (TV shows)
11. listed_in : the genre that the movie or tv show falls under (e.g. International TV Shows, Action, Documentary)
12. description: a summary description of the movie or TV show

Some important notes:
I have made changes directly onto the csv file while I was skimming through the data and I made some significant but helpful changes:
- Louis C.K's works were incorrectly inputted such that the rating feature contained duration data values, such as '86 minutes' instead of 'UR' for 'unrated'. I have realized this mistake when I was trying to make charts related to movie ratings.
- I made sure all of the dates were in Excel's short date format (e.g. 10/12/2023 for 'October 12, 2023').

I know these acts are technically supposed to be reserved for the cleaning, imputing, and data engineering sections, but I wanted to take care of these noticeable mistakes before they mess up the bar/count charts and other visualizations.

# Preparations

Note: this is skipping most of the important details that were once required for Milestone One. The only things here are the commands and functions that are relevant for Milestone 2

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew, kurtosis

# Read the CSV file, make a dataframe
read_csv = pd.read_csv('netflix_titles.csv')
df = pd.DataFrame(read_csv)

# Note - I will only be making this about MOVIES so I can encode duration (the length of the movie) better. Movies also takes 70% of the dataset, so I have plenty of rows left.
df = df[df['type'] == 'Movie']
df['duration'] = df['duration'].str.replace(' min', '').astype(float)
df['duration'].describe()

ModuleNotFoundError: No module named 'numpy'

In [ ]:
df.shape

(6131, 12)

In [ ]:
# Edit: I'm going to try to delete a bunch of movies/rows just because I need as much RAM as possible when I do the One-Hot Encoding... sorry
# there are 6131 rows. I only need 500

# I'm going to remove 5500 rows because 6131 - 5500 = 631
chosen_indices = np.random.choice(df.index, 5500, replace=False)
df_subset = df.drop(chosen_indices)
df = df_subset

the reason why I'm removing so many columns is because the RAM keeps crashing for Milestones 2 and 3 being run in sequence... this also is necessary because the one-hot encoding with the cast list is BEEFY.

In [ ]:
df.shape

(631, 12)

In [ ]:
df.sample(10) # sample 10 random rows

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1580,s1581,Movie,Spirit Riding Free: Ride Along Adventure,"Beth Sleven, Allan Jacobsen, Kevin Wotton","Amber Frank, Bailey Gambertoglio, Sydney Park,...",United States,12/8/2020,2020,TV-Y7,79.0,Children & Family Movies,Join Lucky and her friends on an interactive m...
2635,s2636,Movie,The Dealer,Ahmed Saleh,"Ahmed El Sakka, Khaled El Nabawy, Mai Selim, N...",Egypt,4/25/2020,2010,TV-14,124.0,"Action & Adventure, International Movies","Separated by distance and circumstance, two bi..."
7337,s7338,Movie,Lorai: Play to Live,Parambrata Chatterjee,"Prasenjit Chatterjee, Payel Sarkar, Indrasish ...",India,9/1/2017,2015,TV-14,155.0,"Dramas, International Movies, Sports Movies","Under a government initiative, a retired alcoh..."
1470,s1471,Movie,Alaska Is a Drag,Shaz Bennett,"Martin L. Washington Jr., Maya Washington, Mat...",United States,12/31/2020,2017,TV-MA,83.0,"Dramas, LGBTQ Movies","Tormented by bullies, an aspiring drag star wo..."
6473,s6474,Movie,Chitty Chitty Bang Bang,Ken Hughes,"Dick Van Dyke, Sally Ann Howes, Lionel Jeffrie...","United Kingdom, United States",1/1/2020,1968,G,146.0,"Children & Family Movies, Classic Movies, Come...",Quirky inventor Caractacus Potts and his famil...
2614,s2615,Movie,Boushkash,"Ahmed Yousry, Hazem Fouda","Mohamed Saad, Zeina, Ezzat Abou Aouf, Edward, ...",Egypt,4/28/2020,2008,TV-MA,100.0,"Comedies, International Movies",A former goalkeeper-turned-talent scout embark...
5950,s5951,Movie,Triumph of the Heart,Richard Michaels,"Mario Van Peebles, Susan Ruttan, Lane R. Davis...",United States,10/1/2011,1991,TV-PG,93.0,"Dramas, Sports Movies","This drama tells the tale of Ricky Bell, a pro..."
8168,s8169,Movie,Terra,"Yann Arthus-Bertrand, Michael Pitiot",Vanessa Paradis,France,5/1/2016,2015,TV-PG,98.0,"Documentaries, International Movies",This visually arresting documentary essay refl...
3476,s3477,Movie,The Squid and the Whale,Noah Baumbach,"Jeff Daniels, Laura Linney, Jesse Eisenberg, O...",United States,10/1/2019,2005,R,81.0,"Comedies, Dramas, Independent Movies",This insightful drama looks at the crumbling m...
4781,s4782,Movie,Luciano Mellera: Infantiloide,"Raúl Campos, Jan Suter",Luciano Mellera,Argentina,7/6/2018,2018,TV-14,66.0,Stand-Up Comedy,Argentina's Luciano Mellera emphasizes the hum...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 631 entries, 36 to 8761
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       631 non-null    object
 1   type          631 non-null    object
 2   title         631 non-null    object
 3   director      614 non-null    object
 4   cast          580 non-null    object
 5   country       583 non-null    object
 6   date_added    631 non-null    object
 7   release_year  631 non-null    int64
 8   rating        629 non-null    object
 9   duration      631 non-null    float64
 10  listed_in     631 non-null    object
 11  description   631 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 64.1+ KB

In [ ]:
# Identifying outliers
import numpy as np
import pandas as pd
from scipy import stats

# calculate z-scores for continuous features
z_scores = df.select_dtypes(include=['float64', 'int64']).apply(stats.zscore).abs()

# identifying outlisers using z-score > 3
outliers_df = df[(z_scores > 3).any(axis=1)]

# print the num of outliers for each col
outliers_count = (z_scores > 3).sum()
print(f"Outliers detected based on Z-scores (threshold=3) per column:\n{outliers_count}")

# print the outliers in the form of a df
print("\nOutliers in the form of a dataframe:\n")
print(outliers_df)

Outliers detected based on Z-scores (threshold=3) per column:
release_year    18
duration         4
dtype: int64

Outliers in the form of a dataframe:

     show_id   type                                              title  \
2126   s2127  Movie                               What's Your Raashee?
2543   s2544  Movie  Unbreakable Kimmy Schmidt: Kimmy vs. the Reverend
2721   s2722  Movie                                             Duniya
3142   s3143  Movie                                            Lakshya
5220   s5221  Movie                                          Singapore
5545   s5546  Movie                                              Elaan
6473   s6474  Movie                            Chitty Chitty Bang Bang
6746   s6747  Movie                                Fiddler on the Roof
6765   s6766  Movie                               Five Elements Ninjas
6784   s6785  Movie                                   Forbidden Planet
6864   s6865  Movie                                           Gol Maal
7073   s7074  Movie               Indiana Jones and the Temple of Doom
7393   s7394  Movie                                              Mandi
7519   s7520  Movie                                         Mr. Virgin
7790   s7791  Movie                                     Prelude to War
7881   s7882  Movie                                          Rocky III
7894   s7895  Movie                                    Rosemary's Baby
8142   s8143  Movie            Sword Masters: Two Champions of Shaolin
8260   s8261  Movie                                         The Cruise
8635   s8636  Movie                                          True Grit
8748   s8749  Movie                               Winter of Our Dreams

                  director                                               cast  \
2126    Ashutosh Gowariker  Harman Baweja, Priyanka Chopra, Manju Singh, A...
2543        Claire Scanlon  Ellie Kemper, Jane Krakowski, Tituss Burgess, ...
2721         Ramesh Talwar  Dilip Kumar, Rishi Kapoor, Pran, Amrita Singh,...
3142         Farhan Akhtar  Amitabh Bachchan, Hrithik Roshan, Preity Zinta...
5220        Shakti Samanta  Shammi Kapoor, Padmini, Maria Menado, Shashika...
5545           K. Ramanlal  Vinod Mehra, Rekha, Vinod Khanna, Helen, Madan...
6473            Ken Hughes  Dick Van Dyke, Sally Ann Howes, Lionel Jeffrie...
6746        Norman Jewison  Topol, Norma Crane, Leonard Frey, Molly Picon,...
6765            Cheh Chang  Tien-chi Cheng, Tien Hsiang Lung, Meng Lo, Mic...
6784        Fred M. Wilcox  Leslie Nielsen, Walter Pidgeon, Anne Francis, ...
6864  Hrishikesh Mukherjee  Amol Palekar, Bindiya Goswami, Deven Verma, Ut...
7073      Steven Spielberg  Harrison Ford, Kate Capshaw, Amrish Puri, Rosh...
7393         Shyam Benegal  Shabana Azmi, Smita Patil, Naseeruddin Shah, A...
7519          Anthony Chan  Olivia Cheng, Alfred Cheung, Hu Chin, Chung Pi...
7790           Frank Capra                                                NaN
7881    Sylvester Stallone  Sylvester Stallone, Talia Shire, Burt Young, C...
7894        Roman Polanski  Mia Farrow, John Cassavetes, Ruth Gordon, Sidn...
8142            Cheh Chang  Meng Lo, Sheng Chiang, Li Wang, Siu-Ho Chin, F...
8260        Marek Piwowski  Jan Himilsbach, Stanislaw Tym, Jerzy Dobrowols...
8635        Henry Hathaway  John Wayne, Glen Campbell, Kim Darby, Jeremy S...
8748           John Duigan  Judy Davis, Bryan Brown, Cathy Downes, Baz Luh...

                            country  date_added  release_year rating  \
2126                          India   8/15/2020          2009  TV-PG
2543                  United States   5/12/2020          2020  TV-14
2721                          India    4/1/2020          1984  TV-14
3142                          India  12/15/2019          2004  TV-PG
5220                India, Malaysia  10/15/2017          1960  TV-PG
5545                          India    4/1/2017          1971  TV-14
6473  United Kingdom, United States    1/1/2020          1968      G
6746                  United States    7/1/2020          1971      G
6765                      Hong Kong   9/17/2019          1982      R
6784                  United States   11/1/2019          1956      G
6864                          India  12/31/2019          1979  TV-PG
7073                  United States    1/1/2019          1984     PG
7393                          India    1/1/2020          1983  TV-MA
7519                      Hong Kong   8/16/2018          1984  TV-14
7790                  United States   3/31/2017          1942  TV-14
7881                  United States    8/1/2019          1982     PG
7894                  United States   11/1/2019          1968      R
8142                      Hong Kong   8/16/2018          1980      R
8260                         Poland   10/1/2019          1970  TV-PG
8635                  United States    1/1/2020          1969      G
8748                      Australia   11/1/2016          1981     NR

      duration                                          listed_in  \
2126     203.0   Comedies, International Movies, Music & Musicals
2543     190.0                                           Comedies
2721     170.0   Action & Adventure, Dramas, International Movies
3142     185.0   Action & Adventure, Dramas, International Movies
5220     158.0             Comedies, Dramas, International Movies
5545     143.0  Action & Adventure, Cult Movies, International...
6473     146.0  Children & Family Movies, Classic Movies, Come...
6746     181.0           Classic Movies, Dramas, Music & Musicals
6765     104.0           Action & Adventure, International Movies
6784      98.0  Action & Adventure, Classic Movies, Sci-Fi & F...
6864     137.0     Classic Movies, Comedies, International Movies
7073     119.0  Action & Adventure, Children & Family Movies, ...
7393     155.0   Dramas, Independent Movies, International Movies
7519      86.0             Comedies, Dramas, International Movies
7790      52.0                      Classic Movies, Documentaries
7881     100.0                              Dramas, Sports Movies
7894     137.0           Classic Movies, Horror Movies, Thrillers
8142     101.0           Action & Adventure, International Movies
8260      66.0        Comedies, Cult Movies, International Movies
8635     128.0                             Classic Movies, Dramas
8748      86.0                             Classic Movies, Dramas

                                            description
2126  To protect his family from ruin, Yogesh must m...
2543  It's an interactive Kimmy special! Kimmy's get...
2721  A lawyer defends his childhood friend – and gi...
3142  After dropping out of the army, a spoiled teen...
5220  When his employee disappears in Singapore, Shy...
5545  Journalist Naresh is hired to probe illegal ac...
6473  Quirky inventor Caractacus Potts and his famil...
6746  This adaptation of the musical chronicles the ...
6765  When five ninjas whose fighting styles are bas...
6784  A pulp-fiction sci-fi classic, Forbidden Plane...
6864  When circumstances at work compel Ram to prete...
7073  Indiana Jones, his young sidekick and a spoile...
7393  Forbidden love, fraying loyalties and flagrant...
7519  When a young man ignores a feng shui master’s ...
7790  Frank Capra's documentary chronicles the rise ...
7881  After taking a pounding from a powerful young ...
7894  A woman is thrilled to find out she's pregnant...
8142  Shaolin warrior Tung Chien-chen is injured in ...
8260  When the captain of a pleasant cruise ship mis...
8635  Teenage tomboy Mattie Ross enlists the help of...
8748  After the death of a long-ago lover, married p...

In [ ]:
# Capping duration to be 180 minutes
df['duration'] = np.where(df['duration'] > 180, 180, df['duration'])
# Keeping the floor of the df for release_year to 1985
df['release_year'] = np.where(df['release_year'] < 1985, 1985, df['release_year'])

In [ ]:
# turning all TV-Y related ratings to just 'TV-Y' and merging 'NR' and 'UR' to just 'UR'

df['rating'] = df['rating'].replace(['TV-Y', 'TV-Y7', 'TV-Y7-FV'], 'TV-Y')
df['rating'] = df['rating'].replace(['NR', 'UR'], 'UR')
df['rating'].unique()
df = df.dropna() # this drops rows with any missing values; we're now down to 5188 entries and that's ok because to be honest, I'm a bit lazy and we have a lot of data we can afford to drop
df = df.drop_duplicates() # drop any duplicates

In [ ]:
# I just noticed TV-PG and PG are two different things so I will combine them. The same goes for TV-G and G
df['rating'] = df['rating'].replace(['TV-PG', 'PG'], 'PG')
df['rating'] = df['rating'].replace(['TV-G', 'G'], 'G')

In [ ]:
df['rating'].unique()

array(['R', 'TV-MA', 'PG', 'PG-13', 'TV-14', 'TV-Y', 'G', 'NC-17', 'UR'],
      dtype=object)

## Preparation for Encoding

## Modifying strings
I learned that a lot of names from the string-related features and values have non-English accents on the words, which throws JSON and the ML Model's compiler off.

In [ ]:
import re, unicodedata

# find columns with non-alphanumeric characters
pick_cols = [col for col in df.columns if re.search(r'[^a-zA-Z0-9_]', col)]
print("Problematic Columns:", pick_cols)

Problematic Columns: []

In [ ]:
import unicodedata

# Function to remove accents from a string
def remove_accents(input_str):
    return ''.join(
        c for c in unicodedata.normalize('NFKD', input_str)
        if not unicodedata.combining(c)
    )

# Apply to column names
df.columns = [remove_accents(col) for col in df.columns]

# Clean accents from the 'cast' column (values are lists)
df['cast'] = df['cast'].apply(
    lambda x: [remove_accents(name) for name in x] if isinstance(x, list) else x
)

In [ ]:
# Also, rename or fix the labeling of some of the names because some punctuations don't do well either with Lightgbm
df.columns = df.columns.str.replace('"{}[,\-\.\':]', '', regex=True).str.replace(' ', '_')

In [ ]:
import re, unicodedata

# find columns with non-alphanumeric characters
pick_cols = [col for col in df.columns if re.search(r'[^a-zA-Z0-9_]', col)]
print("Problematic Columns:", pick_cols)

Problematic Columns: []

In [ ]:
# Next, let's change up show_id so it represents the numerical value of the row in which the values are placed in
# I want to make sure all of the titles are alphabetically ordered first from A-Z

df = df.sort_values(by= 'title', ascending=True)

# numerically ordering the values and putting that as the show_id
df.reset_index(inplace = True, drop = True)
df['show_id'] = df.index

# ok, let's drop 'type' and 'title'
print(df.shape)
df.drop(columns=['type', 'title'], inplace=True)

(534, 12)

## Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

labelenc = LabelEncoder()

In [ ]:
# Encoding director
df['director'] = labelenc.fit_transform(df['director'])
df['director']

# Encoding country
df['country'] = labelenc.fit_transform(df['country'])
df['country']

# Encoding rating
rating_mapping = {
    'TV-Y': 0,
    'G' : 1,
    'PG' : 2,
    'PG-13': 3,
    'TV-14': 4,
    'TV-MA': 5,
    'R': 6,
    'NC-17': 7,
    'UR' : 8
}
df['rating'] = df['rating'].map(rating_mapping)

# Encoding dates
# Idea: turn date_added and release_year into 4 separate features:
# Feature 1: date_added_month
# Feature 2: date_added_day
# Feature 3: date_added_year
# Feature 4: release_year

df['date_added'] = pd.to_datetime(df['date_added'])
df['date_added_month'] = df['date_added'].dt.month
df['date_added_day'] = df['date_added'].dt.day
df['date_added_year'] = df['date_added'].dt.year

# I'm going to drop the original date_added
df.drop(columns=['date_added'], inplace=True)

## Normalization and Standardization

In [ ]:
# For dates
import numpy as np

# using cyclical feature engineering to normalize dated elements
# we only need it for months and days because they CYCLE - we don't need to do this for years
# and the reason why we do need both sine and cosine is because months (and days) may map to the same trig value if we're just using cosine or if we're just using sine. We need a sort of "coordinate pair" to represent the month

# for months
# df['date_added_month_cos'] = np.cos(2 * np.pi * df['date_added_month'] / 12)
# df['date_added_month_sin'] = np.sin(2 * np.pi * df['date_added_month'] / 12)

# # for days
# df['date_added_day_cos'] = np.cos(2 * np.pi * df['date_added_day'] / 30)
# df['date_added_day_sin'] = np.sin(2 * np.pi * df['date_added_day'] / 30)

# I have to rescale the values so that the outputs fall in [0,1] instead of [-1,1]
df['date_added_month_cos'] = (1 + np.cos(2 * np.pi * df['date_added_month'] / 12)) / 2
df['date_added_month_sin'] = (1 + np.sin(2 * np.pi * df['date_added_month'] / 12)) / 2

# for days
df['date_added_day_cos'] =(1+ np.cos(2 * np.pi * df['date_added_day'] / 30))/2
df['date_added_day_sin'] = (1+ np.sin(2 * np.pi * df['date_added_day'] / 30))/2

In [ ]:

# Years can be handled with regular standardiztion
# I will comment this out for now just because Naive Bayes doesn't like negative values (and the standard scaler is the cause of that)
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# df['release_year'] = scaler.fit_transform(df[['release_year']])
# df['date_added_year'] = scaler.fit_transform(df[['date_added_year']])

# Milestone 2

## Reflection before I do anything

What is the problem type?
- What immediately comes to mind are classification, clustering, and sentiment analysis
- Idea 1: Classify a movie's TV rating based on its description, director, duration, and cast?
  - Target column = rating; so this would be a supervised learning problem

- Idea 2: Cluster movies based on how similar they are in the release year, the tv rating, the director, the country of filming, and duration
  - No target variable, so this is unsupervised

I think I would like to do the first one (classification) because:
- It has the real-life application of predicting what a movie would be rated based on its content and who is involved in its creation
- At least in my mind, it's easier to measure the performance of the model when its purpose is to conclude discrete values

### Types of Machine Learning Models for Classification (pros and cons):
- Logistic Regression
  - Pros: very simple and interpretable, overfitting is preventable
  - Cons: binary answers only (ex: spam or not spam)
- K-Nearest Neighbors
  - Pros: classifies using closest neighbors (shares the advantages of clustering), non-linear decision boundaries can be modeled
  - Cons: sensitivity to outliers, dependent on how clusters and centroids are defined
- Decision Tree
  - Pros: no need for normalization
  - Cons: prone to overfitting, sensitive to small variations in data
- Random Forest
  - Pros: bagging (and boosting...?) helps it against overfitting
  - Cons: requires careful preparations beforehand
- Naive Bayes
  - Pros: simple and interpretable
  - Cons: assumes feature independence (which might be ok with this dataset?)
- Neural Networks
  - Pros: best ofr highly complex relationships and large scale data.
  - Cons: requires LARGE amounts of data
--------------------------------------
Based on these, my best bets are (1) KNN, (2) Naive Bayes

### My concerns
- How can I do ML on the arrays of strings (cast, listed_in, description)?

- Would description require a sort of sentiment analysis?

Note: I just added the new section in Milestone 1 titled "Other explorations". I just learned that none of the features in this dataset are significantly correlated, so I can totally do Naive Bayes classification because I computationally proved that since none of the features are correlated, then they exist independent of each other. Additionally, Naive Bayes seems simpler to do, as it doesn't require as much hyperparameter tuning as KNN.

## So, I choose Naive Bayes as my Machine Learning Model

In the slides, it also says "It's especially good for tasks like spam filtering or sentiment analysis, where features (like words) are somewhat independent"

Quick run through of how Naive Bayes (NB) works:
- Uses probability to make predictions; calculates the probability that a movie belongs to a rating based on its features using Bayes' Theorem
- TV rating with the highest probability is assigned to the new movie

## Preprocessing 'description', 'cast', and 'listed_in'

The reason why I didn't put this up in Milestone 1 was because (1) I didn't expect to be using Naive Bayes as my model of choice for until I started working on this milestone and (2) I wanted to make it clear that all of the work I did to preprocess description, cast, and listed_in were done for milestone 2

In [ ]:
df['description']

0      After a painful breakup, a trio of party-lovin...
1      After one of his high school students attacks ...
2      Seeking her independence, a young woman moves ...
3      A bumbling Paris policeman is doggedly determi...
4      In parallel love stories, the lives of college...
                             ...
529    After a long stint in the army, an ex-lieutena...
530    Two identical strangers pursue their respectiv...
531    Competing con artists attempt to creatively an...
532    Zack and Miri make and star in an adult film t...
533    A mysterious game sends two brothers flying in...
Name: description, Length: 534, dtype: object

In [ ]:
print(type(df['description']))
print(type(df['cast']))
print(type(df['listed_in']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [ ]:
# Step 0: Import statements
from collections import defaultdict
import string
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
# Step 0.5 for 'description' --- lemmatization or stemming

import spacy
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize spaCy
nlp = spacy.load("en_core_web_sm")

# Lemmatization
def lemmatize_text(text):
    doc = nlp(text)
    return " ".join([token.lemma_ for token in doc])

# Implement/apply lemmatiztn
df['description'] = df['description'].apply(lemmatize_text)

In [ ]:
# Step 1: preprocess the text
stop_words = set(stopwords.words('english')) # stopwords are common words that may throw off the importance of frequency count of relevant words.
# stop words include things like 'the', 'and', 'a', ...

def preprocess(text):
  if isinstance(text, str):
    # process the string only if it's a valid str
    return [name.strip().lower() for name in text.split(',')]
  return []

def preprocess_desc(text):
    if isinstance(text, str):
        # process the string only if it's a valid str
        text = text.lower()  # we want all lowercase
        text = text.translate(str.maketrans('', '', '!"#$%&()*+,-./:;<=>?@[\]^_`{|}~'))  # Remove punctuation besides '
        tokens = text.split()  # tokenize into words
        tokens = [keep_word for keep_word in tokens if keep_word not in stop_words]
        return tokens

    elif isinstance(text, list):
        # (if the list has string elements, you might want to process those)
        tokens = [keep_word for keep_word in tokens if keep_word not in stop_words]
        return text

    else:
        # if it's neither a string nor a list, return an empty list
        return []

# preprocessing the different string vals
cast = [preprocess(cast) for cast in df['cast']]
description = [preprocess_desc(description) for description in df['description']]
listed_in = [preprocess(listed_in) for listed_in in df['listed_in']]

In [ ]:
print(cast)
print(description)
print(listed_in)

[['maia morgenstern', 'olimpia melinte', 'crina semciuc', 'flavia hojda', 'maria dinulescu', 'alex călin', 'vlad logigan', 'sali levent', 'silvia busuioc', 'mihaela mihut'], ['samuel l. jackson', 'john heard', 'kelly rowan', 'clifton collins jr.', 'tony plana'], ['nicole brydon bloom', 'giles matthey', 'taylor nichols', 'alan blumenfeld', 'celeste sully', 'susan davis', 'clayton hoff', 'earnestine phillips'], ['ramzy bedia', 'éric judor', 'benoît magimel', 'kristin scott thomas', 'élodie bouchez', 'édouard baer', 'fred testot', 'omar sy'], ['jacob elordi', 'adan canto', 'radha mitchell', 'tiera skovbye', 'kari matchett', 'tahmoh penikett'], ['anders danielsen lie', 'jon øigarden', 'jonas strand gravli', 'ola g. furuseth', 'maria bock', 'thorbjørn harr', 'jaden smith'], ['elle fanning', 'naomi watts', 'susan sarandon', 'tate donovan', 'linda emond', 'jordan carlos', 'sam trammell', 'maria dizzia', 'tessa albertson'], ['massimo ghini', 'ricky memphis', 'martina stella', 'ralph palka', 'biagio izzo', 'riccardo rossi', 'paola minaccioni'], ['anton yelchin', 'bérénice marlohe', 'olivia thirlby', 'lambert wilson', 'frank langella', 'glenn close'], ['adam sandler', 'drew barrymore', 'rob schneider', 'sean astin', 'lusia strus', 'dan aykroyd', 'amy hill', 'allen covert', 'blake clark', 'maya rudolph'], ['ehan bhat', 'edilsy vargas', 'manisha koirala', 'lisa ray', 'tenzin dalha', 'warina hussain', 'ranjit barot', 'neel tyagi', 'rahul ram', 'diwakar pundir'], ['mila kunis', 'kristen bell', 'kathryn hahn', 'susan sarandon', 'christine baranski', 'jay hernandez', 'cheryl hines', 'peter gallagher', 'justin hartley'], ['cristina vee', 'bryce papenbrook', 'keith silverstein', 'mela lee', 'max mittelman', 'carrie keranen', 'stephanie sheh', 'selah victor', 'ben diskin', 'erin fitzgerald', 'grant george'], ['laura marano', 'gregg sulkin', 'isabella gomez', 'johannah newmarch', 'lillian doucet-roche', 'chanelle peloso', 'barclay hope', 'garfield wilson'], ['will forte', 'domhnall gleeson', 'martin mull', 'joel mchale', 'matt lucas', 'thomas lennon', 'seth green', 'jackie tohn', 'natasha lyonne', 'emmy rossum', 'elvy yost', 'matt walsh', 'john gemberling', 'rick glassman', 'camille guaty'], ['julie walters'], ['laura flannery', 'james cavlo', 'harry hains', 'clemmie dugdale', 'dendrie taylor', 'bryan chesters', 'jennifer dorogi', 'adam lazarre-white', 'nikita ramsey'], ['oscar isaac', 'jessica chastain', 'david oyelowo', 'albert brooks', 'elyes gabel', 'catalina sandino moreno', 'christopher abbott', 'peter gerety', 'alessandro nivola'], ['liev schreiber', 'jeanne tripplehorn', 'joelle carter', 'louise fletcher', 'katie carr', 'renée soutendijk', 'huub stapel', 'michael pas'], ['carmen machi', 'pepón nieto', 'kiti mánver', 'jon kortajarena', 'jimmy castro', 'ricardo nkosi', 'montse pla', 'malcolm treviño-sitté', 'pepa charro', 'esperanza elipe', 'mariana cordero', 'txema blasco'], ['miyu irino', 'saori hayami', 'aoi yuki', 'kensho ono', 'yuki kaneko', 'yui ishikawa', 'megumi han', 'toshiyuki toyonaga', 'mayu matsuoka'], ['ken olin', 'jill eikenberry', 'maureen mueller', 'gregg henry', 'nicholas pryor', 'noble willingham', 'peter michael goetz', 'ron perlman', 'theodore bikel', 'olivia burnette', 'bill allen', 'brad pitt'], ['mandy moore', 'shane west', 'peter coyote', 'daryl hannah', 'lauren german', 'clayne crawford', 'al thompson'], ['isabella acres', 'drake bell', 'emilio estevez', 'nolan gould', 'matthew lillard', 'ray liotta', 'jane lynch', 'ariel winter'], ['patricio castillo', 'sergio bustamante', 'alejandro suárez', 'luz maría jerez', 'bob isaacs', 'tere monroy'], ['sarah jeffery', 'simon paul mutuyimana', 'denis theriault', 'jeremiah sparks', 'steven love', 'cara ricketts', 'jim codrington', 'shamier anderson', 'stephan james', 'lanette ware', 'hugh thompson'], ['p. samuthirakani', 'manikandan', 'madhumathi padmanathan', 'akalyadevi b.', 's i neelambari'], ['josephine langford', 'hero fiennes tiffin', 'selma blair', 'inanna sarkis', 'shane paul mcghie', 'pia mia', 'khadijha red thunder', 'dylan arnold', 'samuel larsen', 'jennifer beals', 'peter gallagher'], ['amitabh bachchan', 'mithun chakraborty', 'danny denzongpa', 'madhavi', 'neelam', 'alok nath', 'rohini hattangadi', 'tinnu anand', 'vikram gokhale', 'archana puran singh'], ['martin l. washington jr.', 'maya washington', 'matt dallas', "christopher o'shea", 'jason scott lee', 'margaret cho', 'kevin daniels', 'john fleck', 'nia peeples', 'adam tomei'], ['youssef chahine', 'yousra', 'hussein fahmy', 'amr abdel-geleel', 'taheya cariocca', 'hesham selim', 'huda sultan', 'ragaa hussein'], ['jeffrey wright', 'ashton sanders', 'regina taylor', 'yahya abdul-mateen ii', 'isaiah john', 'kelly jenrette', 'shakira ja-nai paye'], ['johnny massaro', 'bianca comparato', 'regina braga', 'maria laura nogueira', 'victor mendes', 'thiago amaral', 'rafael primot', 'eduardo mossri', 'rita batata', 'larissa ferrara'], ['javicia leslie', 'jordan calloway', 'richard lawson', 'yvette nicole brown', 'michelle mitchenor', 'amber chardae robinson', 'jasmin brown'], ['kevin spacey', 'annette bening', 'thora birch', 'wes bentley', 'mena suvari', 'chris cooper', 'peter gallagher', 'allison janney', 'scott bakula', 'sam robards'], ['hayden christensen', 'adrien brody', 'jordana brewster', 'tory kittles', 'akon', 'luis da silva jr.', 'lance e. nichols', 'joe chrest'], ['thomas dekker', 'lacey chabert', 'jane singer', 'nehemiah persoff', 'susan boyd', 'robert hays', 'pat musick', 'dom deluise', 'candi milo', 'jeff bennett'], ['oona chaplin', 'natalia tena', 'david verdaguer', 'geraldine chaplin'], ['andré chiang'], ['anjelah johnson-reyes'], ['sanjay mishra', 'seema pahwa', 'rajat kapoor', 'taranjit kaur', 'maya sarao', 'chandrachoor rai', 'namit das', 'brijendra kala', 'alka chawla', 'manu rishi chadha'], ['bailee madison', 'robert capron', 'rachel resheff', 'mavrick moreno', 'whitney goin', 'gary weeks', 'juliana harkavy', 'kevin b. mcglynn', 'jamison stern', 'mia matthews', 'bianca matthews'], ['mohamed henedi', 'bassem samra', 'dorra zarrouk', 'lotfy labib'], ['dan stevens', 'lucy boynton', 'michael sheen', 'mark lewis jones', 'bill milner', 'kristine froseth', 'paul higgins', 'richard elfyn', 'elen rhys', "ross o'hennessy"], ['ahmed eid', 'ayten amer', 'ahmed fouad selim', 'mohsen mansour'], ['priyanka bose', 'vaibhav raj gupta', 'santosh juvekar', 'anangsha biswas', 'ankit raaj', 'kashmira irani', 'kailash waghmare', 'vipin sharma'], ['shah rukh khan', 'kareena kapoor', 'danny denzongpa', 'rahul dev', 'hrishitaa bhatt', 'gerson da cunha', 'subhashini ali', 'umesh mehra', 'sooraj balaji'], ['roy marsden'], ['sam gittins', 'grant masters', 'neerja naik', 'abigail cruttenden', 'kris saddler', 'holly weston', 'david bradley'], ['gina rodriguez', 'ariana greenblatt', 'frances fisher', 'jennifer jason leigh', 'barry pepper', 'shamier anderson', 'finn jones', 'lucius hoyos', 'gil bellows'], ['jack cutmore-scott', 'lili simmons', 'brandon scott', 'chase williamson', 'noureen dewulf', 'seth morris', 'christine donlon', 'trent haaga', 'kahyun kim', 'cynthia rose hall', 'zedrick restauro', 'eric podnar'], ['theeradej wongpuapan', 'sirin horwang', 'ungsumalynn sirapatsakmetha', 'panissara phimpru', 'taksaorn paksukcharern', 'charlie trairat', 'kazuki yano'], ['kelly sheridan', 'kazumi evans', 'claire corlett', 'ashlyn drummond', 'alex kelly', 'tabitha st. germain', 'shannon chan-kent'], ['józef pawłowski', 'zofia domalik', 'szymon bobrowski', 'bartłomiej topa', 'janusz chabior', 'rafał zawierucha', 'antoni pawlicki', 'cezary łukaszewicz', 'danuta stenka', 'jan frycz', 'damian majewski'], ['deep joshi', 'jasmine kaur', 'mohit bhaskar', 'vijay s. kumar', 'prince kanwaljit singh', 'tarlochan singh', 'harsh sethi'], ['luis gerardo méndez', 'brontis jodorowsky', 'joonas saartamo', 'laura birn', 'ilkka koivula', 'ville virtanen', 'raúl villegas', 'miriam balderas', 'ximena guzmán'], ['ashleigh ball', 'lili beaudoin', 'charles demers', 'rebecca husain', 'erin mathews'], ['jerry seinfeld', 'renée zellweger', 'matthew broderick', 'patrick warburton', 'john goodman', 'chris rock', 'kathy bates', 'barry levinson', 'larry king', 'ray liotta'], ['tony mccoy'], ['bert kreischer'], ['gerald anderson', 'julia barretto', 'yayo aguila', 'christian vazquez'], ['cezmi baskın', 'özgü namal', 'umut kurt', 'nazmi kırık', 'bahri beyat', 'meral okay', 'dilber ay', 'şahin irmak', 'oktay kaynarca', 'burak tamdoğan'], ['sunny kaushal', 'rukshar dhillon', 'shriya pilgaonkar', 'parmeet sethi', 'samir soni', 'chaitanya sharma', 'sheeba chaddha', 'akarsh khurana'], ['imran rasheed', 'mittal chouhan', 'trimala adhikari', 'bhushan vikas', 'ravi goswami', 'raghav dutt', 'kumkum chouhan', 'rohan mobarsa'], ['akshay kumar', 'vidya balan', 'ameesha patel', 'shiney ahuja', 'paresh rawal', 'rajpal yadav', 'manoj joshi', 'asrani', 'vikram gokhale', 'rasika joshi'], ['ajay devgn', 'urmila matondkar', 'nana patekar', 'rekha', 'fardeen khan', 'victor banerjee', 'tanuja', 'seema biswas'], ['jules wojciechowski', 'roger craig smith', 'grant george', 'david lodge', 'lindsey alena', 'sandy fox', 'joey lotsko'], ['sandra bullock', 'trevante rhodes', 'john malkovich', 'sarah paulson', 'bd wong', 'jacki weaver', 'rosa salazar', 'danielle macdonald', 'lil rel howery', 'tom hollander'], ['mary joy apostol', 'arnold reyes', 'ku aquino', 'john arcilla', 'dido dela paz', 'elora espano', 'ronnie quizon', 'rolando t. inocencio', 'suzette ranillo', 'angelica c. ferro'], ['raúl arévalo', 'candela peña', 'paulina garcía', 'claude musungayi', 'babou cham', 'lidia nené', 'melina matthews', 'emilio buale', 'mulie jarju', 'jimmy castro', 'fenda drame', 'dairon tallon', 'teresita evuy', 'olivier bony'], ['benjamin dickey', 'alia shawkat', 'josh hamilton', 'charlie sexton', 'sam rockwell', 'wyatt russell', 'steve zahn', 'kris kristofferson', 'richard linklater', 'david kallaway', 'ritchie montgomery'], ['oscar martínez', 'dolores fonzi', 'diego velázquez', 'paulina garcia', 'luis gnecco', 'malena sánchez', 'emilio vodanovich', 'norman briski'], ['sarah paulson', 'mark duplass', 'clu gulager'], ['hedy lamarr'], ['mohamed saad', 'zeina', 'ezzat abou aouf', 'edward', 'hassan hosny', 'ahmed rateb', 'hamdi el sakhawy', 'safaa el-toukhy'], ['wendy raquel robinson', 'ross fleming', 'shondrella avery', 'tammy townsend', 'omar gooding', 'tracy davis', 'veronika bozeman', 'kelly perine', 'valarie pettiford'], ['brad paisley', 'nate bargatze', 'john heffron', 'jon reep', 'sarah tiana', 'mike e. winfield'], ['jason momoa', 'garret dillahunt', 'jill wagner', 'stephen lang', 'sasha rosoff', 'sala baker', 'fraser aitcheson', 'teach grant', 'glenn ennis', 'todd scott', 'zahn mcclarnon', 'brendan fletcher'], ['david attenborough', 'johan rockström'], ['paul walker', 'david belle', 'rza', 'gouchy boy', 'catalina denis', 'ayisha issa', 'carlo rota', 'andreas apergis', 'richard zeman', 'robert maillet'], ['arjun mathur', 'nidhi singh', 'manav vij', 'sheetal thakur', 'sunny hinduja', 'yogendra tikku', 'vijayant kohli'], ['cem gelinoğlu', 'melis babadag', 'ege kökenli', 'müfit kayacan', 'lale başar', 'ali erkazan', 'özlem çakar', 'selen domaç', 'ferdi sancar', 'güven hokna'], ['faizon love', 'kirk fox', 'tony todd', 'pearl thusi', 'cassie clare', 'fiona ramsey', 'neels clasen', 'roxy nel'], ['dulquer salmaan', 'karthika muraleedharan', 'siddique', 'soubin shahir', 'dileesh pothan', 'john vijay', 'chandini sreedharan', 'jinu joseph', 'sujith shankar', 'alencier ley lopez'], ['virginia madsen', 'tony todd', 'xander berkeley', 'kasi lemmons', 'vanessa williams', 'dejuan guy', 'michael culkin', 'stanley desantis'], ['chicco jerikho', 'pevita pearce'], ['johnny depp', 'freddie highmore', 'david kelly', 'helena bonham carter', 'noah taylor', 'missi pyle', 'james fox', 'deep roy', 'christopher lee', 'adam godley', 'annasophia robb', 'julia winter', 'jordan fry', 'philip wiegratz'], ['wilmer valderrama', 'demi lovato', 'sia', 'nia vardalos', 'ashley tisdale', 'avril lavigne', 'g.e.m.', 'john cleese', 'chris harrison', 'dee bradley baker', 'carlos alazraqui'], ['kaustav ghosh', 'jigna bhardwaj', 'chutki', 'rajesh kava', 'mausam', 'guru shambu', 'arun shekar', 'julie tejwani', 'anamaya verma'], ['dick van dyke', 'sally ann howes', 'lionel jeffries', 'gert fröbe', 'anna quayle', 'benny hill', 'james robertson justice', 'robert helpmann', 'heather ripley', 'adrian hall', 'barbara windsor', 'davy kaye', 'alexander doré', 'bernard spear', 'stanley unwin'], ['kostja ullmann', 'alli neumann', 'sascha alexander gersak', 'sophia thomalla', 'merlin rose', 'detlev buck', 'peter kurth', 'anika mauer', 'frederic linkemann', 'bernd hölscher'], ['julian ovenden', 'gemma whelan', 'joely richardson', 'michael landes', 'sally phillips', 'patricia hodge', 'ronni ancona', 'james fox', 'sophie simnett', 'jade ma'], ['shahid kapoor', 'kareena kapoor', 'om puri', 'neha dhupia', 'sunil shetty', 'paresh rawal', 'rajpal yadav', 'shakti kapoor'], ['nurgül yeşilçay', 'celile toyon uysal', 'deniz deha lostar', 'settar tanrıöğen', 'suzan aksoy', 'hüseyin avni danyal', 'jülide kural', 'ragıp savaş'], ['christien anholt', 'andre braugher', 'dan futterman', 'josh lucas', 'clive owen', 'sophie ward', 'sue-ann leeds', 'laura linney'], ['adam sandler', 'kate beckinsale', 'christopher walken', 'david hasselhoff', 'henry winkler', 'julie kavner', 'sean astin', 'joseph castanon', 'jonah hill', 'jake hoffman', 'jennifer coolidge'], ['jim iyke', 'joselyn dumas', 'enyinna nwigwe', 'beverly naya', 'femi adebayo', 'segun arinze', 'padita agu'], ['chiwetel ejiofor', 'martin sheen', 'danny glover', 'jason segel', 'condola rashad', 'lakeith stanfield', 'stacey sargeant', 'vondie curtis-hall'], ['robin weigert', 'maggie siff', 'johnathan tchaikovsky', 'ben shenkman', 'janel moloney', 'emily kinney'], ['adhvik mahajan', 'prasad purandhare', 'sakshi gulati', 'zakir hussain', 'amruta subhash', 'kishore kadam', 'sumeet nijhawan', 'upyendra limaye'], ['gethin anthony', 'frederikke dahl hansen', 'sebastian armesto', 'olivia grant', 'baard owe', 'mille dinesen', 'martin hestbæk', 'tamzin merchant'], ['sarah butler', 'larissa albuquerque', 'kayla wallace', 'matthew maccaull', 'james dean', 'alison wandzura', 'bruce blain', 'natalie grace', 'phillip mitchell'], ['sandra bullock', 'don cheadle', 'matt dillon', 'jennifer esposito', 'william fichtner', 'brendan fraser', 'terrence howard', 'ludacris', 'thandie newton', 'ryan phillippe', 'larenz tate', 'nona gaye', 'michael peña'], ['ramsey nouah', 'chigul', 'sola sobowale', 'ireti doyle', 'ben touitou', 'francis onwochei', 'ememobong nkana', 'emem inwang', 'patrick onyeke'], ['chow yun fat', 'michelle yeoh', 'zhang ziyi', 'chang chen', 'lung hsiung', 'cheng pei-pei', 'fa zeng li', 'xian gao', 'yan hai', 'de ming wang'], ['noriko shinohara', 'ushio shinohara'], ['d.l. hughley'], ['jane turner', 'gina riley', 'glenn robbins', 'peter rowsthorn', 'magda szubanski'], ['madison lawlor', 'montana manning', 'andrew pifko', 'monte markham', 'kamala jones', 'jodi carol harrison', 'seth cassell', 'ronnie clark', 'lissa danshaw', 'j.j. hawkins'], ['martina schöne-radunski', 'hans-heinrich hardt', 'sebastian fräsdorf', 'claudia jacob', 'deleila piasko', 'tobias borchers', 'ruth bickelhaupt'], ['daniel sosa'], ['ricardo quevedo', 'nelson polanía', 'liss pereira', 'brian moreno', 'ana cristina botero', 'jairo ordóñez', 'luis alberto saavedra', 'blanca ligia franco', 'marianne schaller romero', 'shirley marulanda'], ['samuel l. jackson', 'hugh grant', 'lisa kudrow', 'kumail nanjiani', 'tracey ullman', 'samson kayo', 'leslie jones', 'diane morgan', 'cristin milioti', 'joe keery'], ['panisara rikulsurakan', 'kay lertsittichai', 'supanaree sutavijitvong', 'krit jeerapattananuwong', 'warisara jitpreedasakul', 'dujdao vadhanapakorn', 'kim waddoup', 'philaiwan khamphirathat', 'wongsakorn rassamitat', 'bhumibhat thavornsiri'], ['topher grace', 'genesis rodriguez', 'patricia clarkson', 'callan mulvey', 'robin thomas', 'daisy mccrackin'], ['maria bello', 'frank grillo', 'cody horn', 'dustin milligan', 'megan park', 'scott mechlowicz', 'aaron yoo', 'alex goode', 'terence rosemore', 'jesse steccato'], ['nour el-sherif', 'laila elwi', 'mahmoud hemeida', 'safia el-emari', 'mohamed mounir', 'khaled el nabawy', 'seif abdelrahman', 'abdalla mahmoud', 'ahmed fouad selim', 'magdi idris'], ['amanda schull', 'milo ventimiglia', 'shawn ashmore', 'bridget regan', 'jonathan frakes', 'sarah constible', 'spencer drever', 'javier botet'], ['paresh rawal', 'kunal khemu', 'sonu sood', 'soha ali khan', 'johnny lever', 'dilip joshi', 'asrani', 'malay chakrabarty', 'razak khan', 'hrishitaa bhatt'], ['iqbaal ramadhan', 'vanesha prescilla', 'ira wibowo', 'bucek depp', 'happy salma', 'farhan', 'maudy koesnaedi', 'jerome kurnia'], ['rishi kapoor', 'neetu singh', 'aditi vasudev', 'archit krishna', 'akhilendra mishra', 'natasha rastogi', 'manoj bakshi', 'supriya shukla'], ['christopher masterson', 'harry van gorkum', 'rona figueroa', 'matt hickey', 'henry o', 'tom burke', 'robby benson', 'ken shorter', 'john woodnutt', 'lubomir misak'], ['tom rhys harries', 'jessamine-bliss bell', 'patrick stewart', 'andré eriksen', 'richard cordery', 'martin hutson', 'turlough convery', 'delroy brown', 'tamzin merchant'], ['noah kaye bentley', 'brennley brown', 'zach callison', 'nicolas cantu', 'skai jackson', 'marsai martin', 'andre robinson', 'carlos alazraqui', 'jeff bennett', 'grey griffin', 'mary elizabeth mcglynn'], ['dilip kumar', 'rishi kapoor', 'pran', 'amrita singh', 'ashok kumar', 'prem chopra', 'amrish puri', 'satyen kappu', 'mac mohan', 'javed khan'], ['megumi ogata', 'kotono mitsuishi', 'megumi hayashibara', 'yuko miyamura', 'yuriko yamaguchi', 'fumihiko tachiki', 'motomu kiyokawa', 'koichi yamadera', 'takehito koyasu', 'hiro yuki', 'miki nagasawa', 'mugihito', 'akira ishida'], ['jakob dylan', 'ringo starr', 'michelle phillips', 'stephen stills', 'regina spektor', 'beck', 'eric clapton', 'tom petty', 'jackson browne', 'norah jones'], ['vinod mehra', 'rekha', 'vinod khanna', 'helen', 'madan puri', 'brahm bhardwaj'], ['enissa amani'], ['millie bobby brown', 'henry cavill', 'sam claflin', 'helena bonham carter', 'louis partridge', 'burn gorman', 'adeel akhtar', 'susan wokoma', 'frances de la tour', 'fiona shaw'], ['rakesh varre', 'gargeyi', 'vamsi raj nekkanti', 'd p ghani', 'k prasanna'], ['zac efron', 'lily collins', 'kaya scodelario', 'jeffrey donovan', 'angela sarafyan', 'jim parsons', 'john malkovich', 'haley joel osment', 'dylan baker', 'brian geraghty'], ['demet akbağ', 'ata demirer', 'özge borak', 'salih kalyon', 'tanju tuncel', 'serra yılmaz', 'tarık ünlüoğlu', 'ayşenil şamlıoğlu'], ['james ransone', 'vinessa shaw', 'ajiona alexus', 'colin ford'], ['charlie dizon', 'paulo avelino'], ['david a. arnold'], ['johnny depp', 'benicio del toro', 'tobey maguire', 'ellen barkin', 'gary busey', 'christina ricci', 'mark harmon', 'cameron diaz', 'katherine helmond', 'michael jeter', 'craig bierko', 'lyle lovett', 'flea', 'christopher meloni', 'harry dean stanton', 'tim thomerson'], ['frank lammers', 'elise schaap', 'huub stapel', 'monic hendrickx', 'raymond thiry', 'maarten heijmans', 'yannick van de velde'], ['topol', 'norma crane', 'leonard frey', 'molly picon', 'paul mann', 'rosalind harris', 'michele marsh', 'neva small', 'paul michael glaser', 'ray lovelock'], ['ali larter', 'a.j. cook', 'michael landes', "terrence 't.c.' carson", 'jonathan cherry', 'keegan connor tracy', 'sarah carter', 'lynda boyd', 'david paetkau', 'justina machado'], ['tien-chi cheng', 'tien hsiang lung', 'meng lo', 'michael chan wai-man', 'pei hsi chen', 'li wang', 'ke chu'], ['david oyelowo', 'dianne wiest', 'rosie perez', 'teyonah parris', 'hani furstenberg', 'bill raymond'], ['rubén blades', 'bruce greenwood', 'bruce mcgill', "peter o'toole", 'andy garcia', 'nestor carbonell', 'eduardo verástegui', 'catalina sandino moreno', 'eva longoria', 'santiago cabrera', 'adrian alonso', 'oscar isaac', 'm

In [ ]:
# Function to clean each string in the list or as a single string
import re

def clean_string(input_str):
    # Using re.sub for regex replacement
    cleaned_str = re.sub(r'[\"{}\[\],\-\.\':]', '', input_str)
    cleaned_str = cleaned_str.replace(' ', '_')  # Regular replace for spaces
    return cleaned_str


# Clean the 'cast' column, where each entry is a list of actor names
df['cast'] = df['cast'].apply(
    lambda x: [clean_string(name) for name in x] if isinstance(x, list) else clean_string(x)
)

In [ ]:
# Step 2: Build Vocabulary (for all three)
# Init a new empty set for vocab

cast_vocabulary = set()
desc_vocabulary = set()
listed_in_vocabulary = set()

for cast_member in cast:
  if cast_member: # this helps skip empty entries / null elements
    cast_vocabulary.update(cast_member)

for desc_word in description:
  if desc_word:
    desc_vocabulary.update(desc_word)

for listed_in_word in listed_in:
  if listed_in_word:
    listed_in_vocabulary.update(listed_in_word)

# Convert into sorted lists
cast_vocabulary = sorted(list(cast_vocabulary))
desc_vocabulary = sorted(list(desc_vocabulary))
listed_in_vocabulary = sorted(list(listed_in_vocabulary))

# let's see if it works...
print("Cast vocabulary: ", cast_vocabulary)

Cast vocabulary:  ['50 cent', 'a.j. cook', 'a.j. johnson', 'aaditi pohankar', 'aarohi patel', 'aaron eckhart', 'aaron eisenberg', 'aaron jeffery', 'aaron mccusker', 'aaron paul', 'aaron washington', 'aaron yoo', 'aarti patel', 'aarubala', 'abayomi alvin', 'abbas', 'abdalla mahmoud', 'abdel aziz el mountassir', 'abdel imam abdullah', 'abdullrahman al gohani', 'abhay deol', 'abhimanyu singh', 'abigail cruttenden', 'abigail pniowsky', 'abu valayamkulam', 'abun sungkar', 'acha septriasa', 'adam baldwin', 'adam beach', 'adam david thompson', 'adam faraizl', 'adam godley', 'adam gussow', 'adam hochstetter', 'adam lazarre-white', 'adam lefevre', 'adam pally', 'adam rose', 'adam sandler', 'adam tomei', 'adam tuominen', 'adan canto', 'adario strange', 'adarsh gourav', 'adebayo salami', 'adebukola', 'adebukola oladipupo', 'adeel akhtar', 'adel bencherif', 'adeline flaun', 'adewale akinnuoye-agbaje', 'adhisty zara', 'adhvik mahajan', 'adinia wirasti', 'aditi rao hydari', 'aditi vasudev', 'aditya seal', 'adnan siddiqui', 'adrian alonso', 'adrian hall', 'adrian pasdar', 'adriana barraza', 'adrianna chlebicka', 'adrien brody', 'adrián núñez', 'aggy k. adams', 'agha', 'agnieszka żulewska', 'agustín jiménez', 'ahaji issa bello', 'ahd', 'ahmad alhamsho', 'ahmed eid', 'ahmed el sakka', 'ahmed fouad selim', 'ahmed helmy', 'ahmed rateb', 'ahmed sultan', 'aidan gillen', 'ajay devgn', 'ajay raj', 'ajiona alexus', 'akalyadevi b.', 'akara amarttayakul', 'akarsh khurana', 'akhilendra mishra', 'akira akbar', 'akira ishida', 'akon', 'akshay kumar', 'akshaye khanna', 'al pacino', 'al shearer', 'al thompson', 'alaa seif', 'alain hernández', 'alan bates', 'alan blumenfeld', 'alan cumming', 'alan ruck', 'alan tan', 'alan tudyk', 'alankrita sahai', 'alanna ubach', 'alano miller', 'alanoud sajini', 'albert brooks', 'albert hammond jr.', 'albrecht schuch', 'alec secareanu', 'alejandro oliva', 'alejandro suárez', 'alejandro urdapilleta', 'alejandro vera', 'aleksandar seksan', 'alencier ley lopez', 'alessandra de rossi', 'alessandro borghi', 'alessandro nivola', 'alex abbad', 'alex brendemühl', 'alex călin', 'alex d. linz', 'alex ekubo', 'alex gonzaga', 'alex goode', 'alex hassell', 'alex kelly', 'alex kingston', 'alex medina', 'alex neustaedter', 'alex sirvent', 'alex zahara', 'alexa penavega', 'alexander arnold', 'alexander doré', 'alexander siddig', 'alexandra maria lara', 'alexandria lee', 'alexis de anda', 'alfre woodard', 'alfred cheung', 'alfred molina', 'alfred munyua', 'alfred ryder', 'ali al shehhi', 'ali erkazan', 'ali larter', 'ali nuhu', 'alia bhatt', 'alia shawkat', 'alice bellagamba', 'alice englert', 'alice lee', 'alicia fernández', 'alicia keys', 'alicia leigh willis', 'alicia silverstone', 'alicia sánchez', 'alicia witt', 'alison wandzura', 'alistair petrie', 'alka badola kaushal', 'alka chawla', 'allen covert', 'allen maldonado', 'allende blanco', 'alli neumann', 'allison janney', 'alma terzic', 'alok nath', 'alyson stoner', 'alyssa goss', 'aman dhaliwal', 'amanda lawrence', 'amanda peet', 'amanda schull', 'amber chardae robinson', 'amber frank', 'amber heard', 'amber stevens west', 'amber valletta', 'ambujakshi', 'ameesha patel', 'america young', 'amiah miller', 'amit deondi', 'amitabh bachchan', 'amol palekar', 'amr abdel-geleel', 'amr saad', 'amrish puri', 'amrita rao', 'amrita singh', 'amruta subhash', 'amy adams', 'amy hill', 'amy huberman', 'amy landecker', 'amy poehler', 'amy sedaris', 'amy seimetz', 'ana cristina botero', 'ana de armas', 'ana layevska', 'ana polvorosa', 'ana wagener', 'anamaya verma', 'anangsha biswas', 'ananya kashyap', 'anders danielsen lie', 'andie macdowell', 'andre braugher', 'andre robinson', 'andrea frigerio', 'andrea libman', 'andrea ros', 'andreas apergis', 'andrene ward-hammond', 'andrew diaz', 'andrew duncan', 'andrew fiscella', 'andrew hawley', 'andrew pifko', 'andromeda godfrey', 'andrzej dobosz', 'andré chiang', 'andré eriksen', 'andré leon talley', 'andré wilms', 'andrés almeida', 'andy dick', 'andy garcia', 'andy liang', 'andy richter', 'andy samberg', 'andy serkis', 'andy walken', 'anee icha', 'angel alkain', 'angela gibbs', 'angela kinsey', 'angela sarafyan', 'angelica c. ferro', 'angeline yap', 'angga yunanda', 'angira dhar', 'anglie leung', 'anika mauer', 'anil dhawan', 'anil kapoor', 'anisa george', 'anita mui', 'anjan srivastav', 'anjana keerthi', 'anjana sukhani', 'anjelah johnson-reyes', 'ankit raaj', 'ankush dubey', 'anna deavere smith', 'anna faris', 'anna mouglalis', 'anna paquin', 'anna pniowsky', 'anna quayle', 'anna raadsveld', 'anna smołowik', 'anna torv', 'anna wintour', 'annasophia robb', 'anne bancroft', 'anne francis', 'anne hathaway', 'anne-marie duff', 'anne-solenne hatte', 'annette bening', 'annette funicello', 'annisa rawles', 'ansel elgort', 'anson paul', 'anthony anderson', 'anthony andrews', 'anthony bourdain', 'anthony hopkins', 'anthony michael hall', 'anthony quintal', 'anthony vaathiyaar', 'anthony wong chau-sang', 'antoine duléry', 'anton yelchin', 'antonello fassari', 'antoni pawlicki', 'antonio alvarez', 'antonio banderas', 'antony', 'anumegha banerjee', 'anupam kher', 'anurag arora', 'aoi yuki', 'aparna sharma', 'apoorva jha', 'april lawrence', 'archana puran singh', 'archit krishna', 'arfi lamba', 'ari irham', 'ariana greenblatt', 'arie untung', 'ariel winter', 'arisara thongborisut', 'ariyo wahab', 'arié elmaleh', 'arjun gupta', 'arjun kapoor', 'arjun mathur', 'arjunan', 'arkie reece', 'armie hammer', 'arnaud valois', 'arnold reyes', 'arnold schwarzenegger', 'arshad warsi', 'arthur brooks', 'arun bali', 'arun kumar', 'arun shekar', 'arya babbar', 'ashleigh ball', 'ashley bell', 'ashley greene', 'ashley tisdale', 'ashlyn drummond', 'ashok kumar', 'ashok samarth', 'ashok saraf', 'ashton sanders', 'ashutosh rana', 'asivak koostachin', 'aslı bekiroğlu', 'asrani', 'asri handayani', 'ata demirer', 'atchareeya potipipittanakorn', 'audrey tautou', 'audrey wasilewski', 'audu paden', 'august wittgenstein', 'aura garrido', 'aure atika', 'aurore clément', 'avan jogia', 'avril lavigne', 'avtar gill', 'awkwafina', 'aycan koptur', 'ayesha jhulka', 'ayesha takia', 'ayisha issa', 'ayo adesanya', 'ayo ogunshina', 'ayten amer', 'ayushita', 'ayşenil şamlıoğlu', 'b-fine', 'b-real', 'baard owe', 'babatunde aiyegbusi', 'babe cabita', 'babou cham', 'babyjohn choi', 'bahar şahin', 'bahri beyat', 'bailee madison', 'bailey gambertoglio', 'baim wong', 'barbara windsor', 'barclay hope', 'barry atsma', 'barry levinson', 'barry pepper', 'bartłomiej kotschedoff', 'bartłomiej topa', 'barış arduç', 'basil eidenbenz', 'basil harris', 'bassem samra', 'bayoumi fouad', 'baz luhrmann', 'bd wong', 'beatriz medina', 'beatriz olivares', 'beau knapp', 'beck', 'becky ann baker', 'begüm kütük', 'begüm öner', 'belinda effah', 'bella aboulhosn', 'belçim bilgin', 'belén chavanne', 'belén cuesta', 'belén rueda', 'ben affleck', 'ben diskin', 'ben kingsley', 'ben shenkman', 'ben stein', 'ben stiller', 'ben touitou', 'ben whishaw', 'ben york jones', 'benedict wong', 'benicio del toro', 'benjamin a. onyango', 'benjamin bratt', 'benjamin dickey', 'benjamin kyalo', 'benjamin tranié', 'benn northover', 'benny hill', 'benoît magimel', 'berat yenilmez', 'bernard spear', 'bernd hölscher', 'bernie mac', 'bert kreischer', 'beverly naya', 'bharat kaul', 'bhargavi chirmuley', 'bhumibhat thavornsiri', 'bhushan vikas', 'biagio izzo', 'bianca comparato', 'bianca matthews', 'bill allen', 'bill camp', 'bill hader', 'bill irwin', 'bill macy', 'bill milner', 'bill murray', 'bill nunn', 'bill oberst jr.', 'bill raymond', 'bill tangradi', 'billy bob thornton', 'billy burke', 'billy connolly', 'billy zane', 'bimby aquino-yap', 'bindiya goswami', 'binnur kaya', 'bisola aiyeola', 'biswajit chakraborty', 'blac youngsta', 'blake clark', 'blake michael', 'blanca ligia franco', 'blanca suárez', 'blanche gardin', 'blossom chukwujekwu', 'bob isaacs', 'bob stoop', 'bobby campo', 'bogdan iancu', 'boman irani', 'bonnie hunt', 'bora cengiz', 'boris abramov', 'boris ruiz', 'borja luna', 'bouli lanners', 'bowlegged lou', 'boyd holbrook', 'boyz ii men', 'brad garrett', 'brad paisley', 'brad pitt', 'brad schmidt', 'bradley cooper', 'bradley whitford', 'brahm bhardwaj', 'brandon routh', 'brandon scott', 'brandy norwood', 'brec bassinger', 'brendan fletcher', 'brendan fraser', 'brendan gleeson', 'brendan mccarthy', 'brennley brown', 'bresha webb', 'brett dier', 'brian blessed', 'brian dennehy', 'brian doe', 'brian geraghty', 'brian mcguinness', 'brian moreno', 'brian ogola', 'brian setzer', 'brian stepanek', 'brian tyree henry', 'brianne tju', 'bridget moynahan', 'bridget regan', 'brijendra kala', 'broda shaggi', 'bront palarae', 'brontis jodorowsky', 'brooklyn decker', 'bruce blain', 'bruce campbell', 'bruce dinsmore', 'bruce greenwood', 'bruce mcgill', 'bruce spence', 'bruce willis', 'bryan brown', 'bryan chesters', 'bryan cranston', 'bryan leung', 'bryce dallas howard', 'bryce groark', 'bryce papenbrook', 'bryshere gray', "brían f. o'byrne", 'bucek depp', 'bukky ajayi', 'bun-hay mean', 'burak tamdoğan', 'burcu kara', 'burgess meredith', 'burn gorman', 'burt grinstead', 'burt young', 'busta rhymes', 'buğra gülsoy', 'bérénice bejo', 'bérénice marlohe', 'caetlyn collins', 'caleb landry jones', 'callan mulvey', 'callie hope haverda', 'calvin jeremy', 'calvin ka-sing cheng', 'cam clarke', 'cameron diaz', 'cameron jack', 'camila mendes', 'camille cottin', 'camille guaty', 'candace bushnell', 'candela peña', 'candela recio', 'candi milo', 'candice bergen', 'cao bingkun', 'cara ricketts', 'carey mulligan', 'carice van houten', 'carissa putri', 'carl safina', 'carl weathers', 'carl windom carlito', 'carlo rota', 'carlos alazraqui', 'carlos areces', 'carlos ballarta', 'carlos librado "nene"', 'carlos piñeyro', 'carmen ferland', 'carmen machi', 'carol kane', 'carol sutton', 'carolina bang', 'caroline langrishe', 'carrie keranen', 'cary joji fukunaga', 'casey affleck', 'casper van dien', 'cassandra ciangherotti', 'cassie clare', 'catalina denis', 'catalina sandino moreno', 'catherine jacob', 'catherine keener', 'cathy cavadini', 'cathy downes', 'cathy weseluck', 'cedric the entertainer', 'celeste henderson', 'celeste sully', 'celestial', 'celia weston', 'celile toyon uysal', 'celine menville', 'cem gelinoğlu', 'cemal hünal', 'cengiz bozkurt', 'cerina vincent', 'cesar montano', 'cezary łukaszewicz', 'cezmi baskın', 'cha-lee yoon', 'chad michael collins', 'chadwick boseman', 'chaitanya sharma', 'chalet lizette brannan', 'chandan roy sanyal', 'chandini sreedharan', 'chandra liow', 'chandrachoor rai', 'chandrachur singh', 'chanelle peloso', 'chang chen', 'chanté adams', 'charlene choi', 'charles demers', 'charles etubiebi', 'charles grodin', 'charles inojie', 'charles mesure', 'charles terrier', 'charlie bewley', 'charlie dizon', 'charlie plummer', 'charlie sexton', 'charlie sheen', 'charlie tahan', 'charlie trairat', 'charlotte gabris', 'charlotte le bon', 'charmaine fong', 'charudatta bhagwat', 'chase williamson', 'cheech marin', 'chelsea islan', 'cheng pei-pei', 'cher', 'cheryl hines', 'chetan pandit', 'chi mcbride', 'chiaki kuriyama', 'chicco jerikho', 'chien sun', 'chigul', 'chimezie imo', 'chin shih-chieh', 'chinmay mandlekar', 'chitrashi rawat', 'chittaranjan tripathi', 'chiwetel ejiofor', 'chloe coleman', 'chloe levine', 'chloë grace moretz', 'cho min-soo', 'choi jung-woo', 'choi si-won', 'choi woo-shik', 'chow yun fat', 'chris chalk', 'chris cooper', 'chris elliott', 'chris evans', 'chris gibbs', 'chris harrison', 'chris hemsworth', 'chris messina', "chris o'dowd", 'chris okagbue', 'chris parnell', 'chris pratt', 'chris rock', 'chris sanders', 'chrissy metz', 'christian bale', 'christian kane', 'christian madsen', 'christian mckay', 'christian rubeck', 'christian slater', 'christian sugiono', 'christian vazquez', 'christien anholt', 'christina hendricks', 'christina moore', 'christina ricci', 'christine baranski', 'christine donlon', 'christine hakim', 'christopher abbott', 'christopher berry', 'christopher lee', 'christopher martin', 'christopher masterson', 'christopher mcdonald', 'christopher meloni', "christopher o'shea", 'christopher plummer', 'christopher reid', 'christopher walken', 'chua kah joo', 'chuck d.', 'chukwuemeka okoroafor', 'chumel torres', 'chung ping geung', 'chunky pandey', 'chutki', 'chyler leigh', 'ciarán hinds', 'cihan ercan', 'cindy crawford', 'cindy robinson', 'claire bloom', 'claire corlett', 'claire danes', 'clancy brown', 'clara read', 'clara rugaard', 'clark duke', 'claude musungayi', 'claudia canal', 'claudia jacob', 'claudia placer', 'claudio amendola', 'clayne crawford', 'clayton hoff', 'clem tibber', 'clemens schick', 'clemmie dugdale', 'cliff curtis', 'clifton collins jr.', 'clifton powell', 'clint eastwood', 'clive owen', 'cloris leachman', 'clu gulager', 'clémentine poidatz', 'cody cameron', 'cody fern', 'cody horn', 'cody mcmains', 'cole sprouse', 'colin firth', 'colin ford', 'colm feore', 'colt crawford', 'common', 'condola rashad', 'constance dollé', 'cooper lundeen', 'cory hardrict', 'cory nichols', 'cory oliver', 'courteney cox', 'courtney b. vance', 'courtney eaton', 'craig bierko', 'craig francis', 'craig mack', 'craig robinson', 'crina semciuc', 'crispin glover', 'cristin milioti', 'cristina vee', 'cuauhtémoc duque', 'cuba gooding jr.', 'cynthia kirchner', 'cynthia nixon', 'cynthia rose hall', 'd p ghani', 'd.c. young fly', 'd.l. hughley', 'da brat', 'dady brieva', 'dain said', 'dairon tallon', 'daisuke ono', 'daisy head', 'daisy lightfoot', 'daisy mccrackin', 'daisy ridley', 'dakore akande', 'dakota fanning', 'dale carley', 'dale dickey', 'dalila bela', 'dalip tahil', 'damian majewski', 'damian young', 'damilola adegbite', 'damilola ogunsi', 'daminee basu', 'dan aykroyd', 'dan castellaneta', 'dan fogler', 'dan futterman', 'dan stevens', 'dana abdullilah', 'dana jabr', 'dana woods', 'dane cook', 'daniel bacon', 'daniel bernhardt', 'daniel brochu', 'daniel brühl', 'daniel duval', 'daniel ewing', 'daniel faraldo', 'daniel horvath', 'daniel radcliffe', 'daniel sosa', 'daniel stern', 'daniel zovatto', 'daniela rubio', 'danielle macdonald', 'danielle von zerneck', 'danish taimoor', 'dannia salsabila', 'danny chan', 'danny corbo', 'danny denzongpa', 'danny devito', 'danny flaherty', 'danny glover', 'danny huston', 'danny masterson', 'danny trejo', 'danny woodburn', 'danuta stenka', 'daphne sheldrick', 'dara singh', 'darby camp', 'darcy rose byrnes', 'darren shahlavi', 'darren wang', 'darshan jariwala', 'darshan kumar', 'daryl hannah', 'daryl sabara', 'dascha polanco', 'dattanna', 'dave chappelle', 'daveed diggs', 'david a. arnold', 'david a.r. white', 'david abraham', 'david arquette', 'david asavanond', 'david attenborough', 'david belle', 'david benger', 'david bradley', 'david calder', 'david campbell', 'david carradine', 'david deluise', 'david dencik', 'david hasselhoff', 'david hendrawan', 'david hyde pierce', 'david jensen', 'david kallaway', 'david kaye', 'david kelly', 'david koechner', 'david lodge', 'david mazouz', 'david michie', 'david morse', 'david ogden stiers', 'david oyelowo', 'david paetkau', 'david schwimmer', 'david schütter', 'david shackelford', 'david spade', 'david strathairn', 'david verdaguer', 'david villegas', 'david yip', 'david zayas', 'davina leonard', 'davy kaye', 'dax shepard', 'daya shankar pandey', 'dayo akinpelu', 'de ming wang', 'dean cain', 'dean norris', "dean o'gorman", 'dean stockwell', 'dean-charles chapman', 'debbi morgan', 'deborah rush', 'debra winger', 'deddy sutomo', 'dede yusuf', 'dee bradley baker', 'dee dee green', 'deep joshi', 'deep roy', 'deepak dobriyal', 'deepak tijori', 'deepankar de', 'deepika amin', 'deepika padukone', 'dejuan guy', 'deleila piasko', 'delroy brown', 'demet akbağ', 'demet özdemir', 'demetri goritsas', 'demetri martin', 'demetrius grosse', 'demi lovato', 'demián bichir', 'dendrie taylor', 'denis arndt', 'denis theriault', 'denise boutte', 'deniz deha lostar', 'dennis adhiswara', 'dennis haysbert', 'dennis hopper', 'denny sumargo', 'denzel washington', 'denzil smith', 'deon richmond', 'deray davis', 'derek jacobi', 'derek luke', 'derek mears', 'dermot mulroney', "derrick o'connor", 'desiree densiti', 'desmond llewelyn', 'detlev buck', 'devadarshini chetan', 'deven verma', 'devid striesow', 'devon terrell', 'dewi hughes', 'dewi irawan', 'dewi sandra', 'dhanu gowda', 'dharmendra', 'dheirya sonecha', 'dian sastrowardoyo', 'diana bovio', 'diana fernández pérez', 'diana penty', 'diana raval', 'diane delano', 'diane kruger', 'diane lane', 'diane morgan', 'dianne wiest', 'dick van dyke', 'dido dela paz', 'diedrich bader', 'diego velázquez', 'diksha sharma', 'dilber ay', 'dileesh pothan', 'dilip joshi', 'dilip kumar', 'dilip prabhavalkar', 'diljit dosanjh', 'dillon fontana', 'dimas dinang', 'dimple kapadia', 'dina pathak', 'dinah shore', 'dino andrade', 'dino morea', 'dipannita sharma', 'divya seth', 'divyendu sharma', 'diwakar pundir', 'dj premier', 'dj scratch', 'djenar maesa ayu', 'dolly minhas', 'dolores fonzi', 'dom deluise', 'domhnall gleeson', 'dominic mafham', 'dominic power', 'dominique fishback', 'don cheadle', 'donald faison', 'dong-seok ma', 'donnie yen', 'donny alamsyah', 'doria tillier', 'dorra zarrouk', 'doug haley', 'douglas henshall', 'douglas hodge', 'douglas tait', 'doyin abiola', 'dr. dre', 'drake bell', 'drew barrymore', 'drew tanner', 'dujdao vadhanapakorn', 'dulquer salmaan', 'duncan joiner', 'durai ramesh', 'durgesh kumar', 'dustin hoffman', 'dustin milligan', 'dwight yoakam', 'dylan arnold', 'dylan baker', 'dylan gelula', 'dylan henry lau', 'dylan kenin', 'dylan mcdermott', 'dylan sprouse', 'e-40', 'eadie del rubio', 'earl holliman', 'earnestine phillips', 'ebru cündübeyoğlu', 'ed harris', 'eda ece', 'eddie kaye thomas', 'eddie murphy', 'edi gathegi', 'edilsy vargas', 'edith fields', 'eduardo mossri', 'eduardo rosa', 'eduardo verástegui', 'edward', 'edward kagutuzi', 'edward norton', 'ege kökenli', 'ehan bhat', 'eiza gonzález', 'elaine jin', 'elarica johnson', 'elen rhys', 'elena del rubio', 'elena kazan', 'eligio meléndez', 'elijah wood', 'elio germano', 'elisabeth röhm', 'elise neal', 'elise schaap', 'eliseo mancilla de la cruz', 'elisha cook jr.', 'elitsa bako', 'eliza bennett', 'elizabeth banks', 'elizabeth bogush', 'elizabeth hoffman', 'elizabeth marvel', 'elizabeth peña', 'elizabeth reaser', 'ella jazz', 'elle fanning', 'ellen barkin', 'ellen burstyn', 'ellen page', 'ellie kemper', 'elora espano', 'elozonam ogbolu', 'elsa biedermann', 'elvina ibru', 'elvira devinamira', 'elvis nolasco', 'elvy yost', 'elyes gabel', 'ema horvath', 'emad al youssef', 'emem inwang', 'ememobong nkana', 'emilio buale', 'emilio estevez', 'emilio palacios', 'emilio vodanovich', 'emily jackson', 'emily kinney', 'emily morris', 'emily mortimer', 'emily ratajkowski', 'emjay anthony', 'emma roberts', 'emma stone', 'emma suárez', 'emma thompson', 'emma watson', 'emmaline henry', 'emmy rossum', 'emory cohen', 'emre kınay', 'engin altan düzyatan', 'enid-raye adams', 'enissa amani', 'enoch frost', 'enrique villén', 'entsar', 'enyinna nwigwe', 'enzo cilenti', 'erasmo carlos', 'erdal tosun', 'eric cantona', 'eric christian olsen', 'eric clapton', 'eric godon', 'eric heister', 'eric idle', 'eric jungmann', 'eric nelsen', 'eric podnar', 'eric tsang', 'erick sermon', 'erin davie', 'erin fitzgerald', 'erin mathews', 'erkan kolçak köstendil', 'ernesto sevilla', 'ernie joseph', 'erol gedik', 'ersa mayori', 'esai morales', 'esperanza elipe', 'esther goh', 'ethan hawke', 'ethan suplee', 'eucharia anunobi', 'eui-sung kim', 'eva green', 'eva longoria', 'eva mendes', 'evan jonigkeit', 'evan smith', 'eve best', 'ewen leslie', 'ezgi eyüboğlu', 'ezgi mola', 'ezra miller', 'ezzat abou aouf', 'fa zeng li', 'faisal al omairi', 'faizon love', 'famke janssen', 'fardeen khan', 'farhan', 'farhan akhtar', 'farida jalal', 'fatima jabbe', 'fatima sana shaikh', 'fayez al-malki', 'fayez kazak', 'fedi nuril', 'felicity jones', 'felipe abib', 'felipe garcía vélez', 'felix cees

In [ ]:
print("Description vocab: ", desc_vocabulary)

Description vocab:  ["'", "'s", '10', '100', '11', '1126', '12', '12th', '14', '15', '16', '17', '18th', '1900s', '1905', '1920s', '1930', '1958', '1960', '1970', '1980', '1981', '1983', '1990', '1992', '20', '2003', '2010', '2014', '2018', '2020', '2092', '20th', '21st', '25', '28', '3', '30', '34', '36', '40', '40th', '501', '51st', '60', '8', '80', '9', '90s', 'aardman', 'abandon', 'abbey', 'abduct', 'abductor', 'abel', 'ability', 'able', 'abominable', 'abortion', 'abound', 'abruptly', 'absence', 'abuse', 'academic', 'academy', 'acapulco', 'accept', 'acceptance', 'access', 'accident', 'accidentally', 'accompany', 'accomplice', 'accountant', 'accuse', 'acha', 'achieve', 'achmed', 'across', 'act', 'action', 'activist', 'activity', 'actor', 'actress', 'actually', 'adaptation', 'addict', 'aditi', 'adjust', 'admirer', 'admit', 'adore', 'adrien', 'adult', 'advanced', 'adventure', 'adventurous', 'affair', 'affection', 'affectionate', 'afghan', 'afghanistan', 'afloat', 'africa', 'african', 'age', 'aged', 'agency', 'agent', 'ago', 'agonizing', 'agree', 'ail', 'aimless', 'aisha', 'alaska', 'alaskan', 'album', 'alcoholic', 'alex', 'alexis', 'alfonso', 'alfred', 'alicia', 'alien', 'allegedly', 'alluring', 'alone', 'along', 'aloof', 'alps', 'already', 'also', 'altair', 'altar', 'alter', 'alternate', 'always', 'amaia', 'amani', 'amateur', 'amazing', 'ambitious', 'ambush', 'america', 'american', 'amid', 'amidst', 'amish', 'among', 'amstell', 'amsterdam', 'amuse', 'amusing', 'amy', 'ana', 'ancient', 'anda', 'andrei', 'andries', 'andré', 'anemona', 'anew', 'ang', 'angeles', 'angelino', 'angels', 'animal', 'animate', 'animation', 'animations', 'anniversary', 'another', 'answer', 'antic', 'anticipate', 'antique', 'anything', 'apart', 'apartment', 'apathetic', 'apatow', 'apocalyptic', 'apollo', 'app', 'apparent', 'appear', 'appearance', 'appoint', 'approach', 'aramaki', 'archaeological', 'architect', 'arduous', 'area', 'argentina', 'argentine', 'ariya', 'arm', 'armed', 'army', 'arnold', 'around', 'arrange', 'arranged', 'arrest', 'arrive', 'arrogant', 'art', 'artist', 'artistic', 'asia', 'asians', 'aspect', 'aspire', 'aspiring', 'assailant', 'assassin', 'assassination', 'assault', 'assert', 'astray', 'astrological', 'astute', 'atheistic', 'athlete', 'atlanta', 'attack', 'attempt', 'attenborough', 'attend', 'attitude', 'attorney', 'attract', 'aucoin', 'audio', 'audition', 'aunt', 'australia', 'australian', 'author', 'authority', 'autism', 'avalanche', 'avenge', 'avert', 'avoid', 'await', 'award', 'away', 'awkward', 'ax', 'ayahuasca', 'aymar', 'ayvalık', 'baby', 'bachelor', 'back', 'backdrop', 'backstage', 'backwater', 'bad', 'baggage', 'balboa', 'band', 'bank', 'banker', 'bar', 'barber', 'barbie', 'bare', 'bargain', 'bargatze', 'barry', 'base', 'bash', 'battle', 'bay', 'baztan', 'bead', 'bear', 'beast', 'beat', 'beautiful', 'beauty', 'beckett', 'become', 'bee', 'beer', 'befriend', 'begin', 'beginning', 'behavior', 'behind', 'beleaguered', 'belgium', 'belief', 'believe', 'bell', 'bella', 'belly', 'beloved', 'ben', 'beneath', 'benjamin', 'benjie', 'benni', 'bent', 'bequeath', 'bernie', 'beset', 'bespectacled', 'best', 'bet', 'betrayal', 'better', 'beyond', 'bhangra', 'bheem', 'bible', 'bickering', 'bicycle', 'bid', 'bieber', 'big', 'bigfoot', 'bill', 'billing', 'billion', 'billy', 'biodiversity', 'biographical', 'biopic', 'bipolar', 'birth', 'birthday', 'bite', 'bitter', 'bitterly', 'bizarre', 'black', 'blacklist', 'blackmail', 'blahnik', 'blend', 'blind', 'blister', 'blockbuster', 'blood', 'bloody', 'bloom', 'blossom', 'blue', 'bobby', 'body', 'bodybuilder', 'bodyguard', 'bogus', 'bold', 'bollywood', 'bomb', 'bond', 'book', 'bookbinder', 'bookworm', 'boom', 'boost', 'border', 'bored', 'boredom', 'bosnian', 'boss', 'bottom', 'bouman', 'bowler', 'boxer', 'boxing', 'boy', 'boyfriend', 'boys', 'brad', 'brain', 'brainy', 'brand', 'bravely', 'brazilian', 'breach', 'break', 'breakup', 'breast', 'breezy', 'brief', 'brij', 'brilliantly', 'bring', 'britain', 'british', 'brittania', 'broadcast', 'broke', 'brooding', 'brooklyn', 'brosnan', 'brothel', 'brother', 'bruise', 'brutal', 'bubble', 'bublé', 'buccaneer', 'buck', 'bud', 'budapest', 'buddhism', 'buddy', 'bug', 'bugs', 'build', 'building', 'bullied', 'bully', 'bumble', 'bundy', 'bureaucratic', 'burgle', 'burn', 'business', 'businessman', 'busking', 'button', 'buy', 'cabbie', 'cabin', 'cadet', 'cafe', 'cagey', 'cairo', 'california', 'caliph', 'call', 'callous', 'calm', 'camaraderie', 'camera', 'camp', 'campaign', 'campus', 'canada', 'cancer', 'candy', 'candyman', 'cannery', 'canyon', 'capacity', 'cape', 'caper', 'captain', 'captivate', 'captive', 'captor', 'capture', 'car', 'caractacus', 'card', 'care', 'career', 'carla', 'carlsen', 'carlton', 'carman', 'carol', 'carolina', 'carry', 'cartel', 'case', 'cast', 'caste', 'casual', 'cat', 'catch', 'catholics', 'cause', 'cave', 'cedric', 'celebrate', 'celebration', 'celebrity', 'cell', 'center', 'central', 'century', 'ceo', 'certain', 'chain', 'challenge', 'champ', 'champion', 'chance', 'change', 'chaos', 'chaotic', 'chapter', 'character', 'characteristic', 'charismatic', 'charm', 'charming', 'charo', 'chase', 'chatterbox', 'chaturthi', 'chauffeur', 'chauvinist', 'cheap', 'cheat', 'cheek', 'cheer', 'cheerleader', 'chef', 'chemical', 'chen', 'chennai', 'chess', 'chest', 'chhota', 'chiang', 'chien', 'chieng', 'child', 'childhood', 'chill', 'chilling', 'chilly', 'chime', 'china', 'choice', 'choose', 'chris', 'christmas', 'chronicle', 'chun', 'cia', 'cinema', 'circle', 'circumstance', 'circus', 'city', 'civil', 'civilian', 'clan', 'clash', 'class', 'classic', 'classmate', 'claus', 'clawdeen', 'clean', 'cleansing', 'clear', 'clerk', 'clever', 'client', 'climate', 'cling', 'clock', 'close', 'club', 'clue', 'clutch', 'co', 'coach', 'coast', 'coastal', 'coat', 'coco', 'cogburn', 'cohort', 'cold', 'coleman', 'collaborator', 'collapse', 'collect', 'college', 'collide', 'colonial', 'color', 'coma', 'comatose', 'combat', 'combination', 'come', 'comedian', 'comedians', 'comedic', 'comedy', 'comer', 'comes', 'comfort', 'comfortable', 'comic', 'comically', 'comicstrip', 'command', 'commander', 'commando', 'commissioner', 'commit', 'communicate', 'community', 'company', 'compel', 'compelling', 'compete', 'competition', 'complete', 'complex', 'complicate', 'complicated', 'complication', 'compose', 'comprise', 'con', 'concentration', 'concern', 'concerned', 'concert', 'condemnation', 'condition', 'confection', 'confederacy', 'conference', 'confess', 'confiscate', 'conflict', 'conflicted', 'conflicting', 'confound', 'confront', 'congenial', 'connection', 'connor', 'consciousness', 'consecutive', 'consequence', 'conservative', 'consider', 'conspiracy', 'conspire', 'consume', 'contend', 'contest', 'contractor', 'control', 'conundrum', 'convenience', 'converge', 'convict', 'conviction', 'convince', 'cop', 'cope', 'copy', 'corner', 'corrupt', 'corruption', 'cost', 'could', 'councilman', 'counterculture', 'counterfeit', 'counterpart', 'country', 'countryside', 'coup', 'couple', 'courage', 'course', 'court', 'courtroom', 'cousin', 'cover', 'coveted', 'cowboy', 'cozy', 'crack', 'crafty', 'cramp', 'cranky', 'crash', 'crass', 'craze', 'crazy', 'create', 'creation', 'creative', 'creatively', 'creator', 'creature', 'creed', 'creep', 'crew', 'crime', 'criminal', 'cris', 'crisis', 'crop', 'cross', 'crowd', 'cruel', 'cruise', 'crumble', 'crush', 'crusty', 'cuarón', 'cuisine', 'cullen', 'culminate', 'cult', 'culture', 'cummings', 'cunning', 'curious', 'curiously', 'curmudgeon', 'current', 'curse', 'cursed', 'custody', 'cut', 'cyberpunk', 'da', 'dachshund', 'dad', 'daddy', 'daily', 'dakota', 'dalton', 'damage', 'dance', 'dancer', 'dancing', 'danger', 'dangerous', 'daniel', 'danish', 'danny', 'daring', 'dark', 'date', 'dating', 'daughter', 'daunting', 'david', 'day', 'dazzle', 'dc', 'de', 'dea', 'dead', 'deadly', 'deaf', 'deal', 'dealer', 'dealing', 'dear', 'death', 'debonair', 'debris', 'debt', 'debut', 'decade', 'deceased', 'deception', 'decide', 'dedicate', 'deduction', 'deed', 'deep', 'deeply', 'defend', 'defiant', 'defraud', 'degollado', 'dejected', 'delhi', 'deliver', 'delve', 'demand', 'democracy', 'demon', 'denmark', 'dentist', 'departure', 'depict', 'deprecate', 'depressed', 'depression', 'depth', 'derail', 'desert', 'deserter', 'design', 'designer', 'desolation', 'desperado', 'desperate', 'desperately', 'despite', 'destine', 'destroy', 'destruction', 'detach', 'detection', 'detective', 'detention', 'determined', 'detroit', 'devastating', 'develop', 'device', 'devilishly', 'devoid', 'devotion', 'diagnose', 'diametrically', 'diana', 'dicey', 'die', 'difference', 'different', 'difficult', 'dig', 'dilan', 'dimension', 'dinner', 'diplomat', 'direct', 'direction', 'director', 'disabled', 'disappear', 'disappearance', 'disaster', 'disastrous', 'discouragement', 'discover', 'discovery', 'discuss', 'disease', 'disgraced', 'dishearten', 'dishonesty', 'dismisse', 'disney', 'disorder', 'disown', 'dispatch', 'display', 'disrupt', 'dissatisfied', 'distance', 'distant', 'distressing', 'disturb', 'disturbing', 'dive', 'divided', 'divorce', 'dizzying', 'dl', 'doctor', 'document', 'documentarian', 'documentary', 'dodge', 'dog', 'doggedly', 'doll', 'dollar', 'domestic', 'domesticity', 'dominate', 'donkey', 'donor', 'door', 'dose', 'double', 'doubt', 'doug', 'downward', 'draco', 'dracula', 'drag', 'dragon', 'drake', 'drama', 'dramatic', 'dramatize', 'draw', 'dream', 'dreamer', 'drifter', 'drive', 'driver', 'droid', 'drone', 'drop', 'drudgery', 'drug', 'dubai', 'due', 'dull', 'dump', 'dunham', 'duo', 'dutch', 'dwarf', 'dwelling', 'dynamic', 'dynasty', 'dysfunctional', 'e', 'eager', 'eagle', 'earle', 'early', 'earn', 'earth', 'earthquake', 'eastern', 'easy', 'eat', 'eccentric', 'eco', 'economist', 'edge', 'edinburgh', 'editor', 'educational', 'edward', 'effect', 'effort', 'egan', 'egg', 'ego', 'egyptian', 'eid', 'eight', 'elaborate', 'elect', 'election', 'element', 'elephant', 'elf', 'elite', 'elixir', 'elle', 'elliot', 'elliott', 'else', 'elude', 'elusive', 'elías', 'emancipate', 'embark', 'embarrassing', 'embrace', 'embroil', 'emerge', 'emmy', 'emotional', 'emotionally', 'emphasize', 'empire', 'employee', 'employer', 'enchanted', 'encounter', 'end', 'endanger', 'endangered', 'endeavor', 'endemic', 'endurance', 'endure', 'enemy', 'engage', 'engineer', 'engineering', 'england', 'enigmatic', 'enissa', 'enlist', 'enola', 'enough', 'enrage', 'ensemble', 'enslave', 'ensue', 'ensure', 'entangle', 'enter', 'enterprise', 'entertain', 'entertainer', 'entertainment', 'entire', 'entity', 'entrepreneur', 'entry', 'environment', 'environmentalist', 'epic', 'epps', 'equestria', 'ericka', 'erupt', 'eruption', 'escamilla', 'escape', 'espouse', 'esra', 'essay', 'establish', 'estranged', 'ethiopian', 'ethnic', 'etiquette', 'europe', 'european', 'eva', 'evade', 'evangelist', 'eve', 'even', 'evening', 'event', 'eventful', 'ever', 'everfree', 'every', 'everyone', 'everything', 'eviction', 'evidence', 'evil', 'evolve', 'ex', 'exam', 'examine', 'except', 'exchange', 'excited', 'excitement', 'exclusive', 'executive', 'exercise', 'exhilarate', 'exist', 'existence', 'exorcism', 'expat', 'expectation', 'experience', 'experiment', 'expert', 'explanation', 'explore', 'explosive', 'expose', 'exposure', 'expressive', 'extension', 'extinction', 'extra', 'extreme', 'eyed', 'f', 'facade', 'face', 'faceless', 'facilitate', 'facility', 'fact', 'factor', 'factory', 'fading', 'fahri', 'fail', 'failure', 'fair', 'fairy', 'faith', 'fake', 'fall', 'falls', 'fame', 'famed', 'family', 'famous', 'fan', 'fangtastic', 'fantastical', 'fantasy', 'far', 'faraway', 'farm', 'farmer', 'farrelly', 'fashioned', 'fast', 'fate', 'father', 'fatherly', 'favorite', 'fbi', 'fear', 'feature', 'feed', 'feel', 'feeling', 'feisty', 'feline', 'fellow', 'female', 'feminism', 'fend', 'feng', 'ferry', 'festival', 'fetish', 'fi', 'fiancé', 'fiancée', 'fiction', 'fictitious', 'fidelity', 'field', 'fierce', 'fiery', 'fievel', 'fifteen', 'fight', 'fighter', 'fighting', 'figure', 'file', 'fill', 'film', 'final', 'finally', 'finance', 'financial', 'find', 'finland', 'fire', 'first', 'firuzan', 'fisherman', 'five', 'fix', 'flagrant', 'flame', 'flanner', 'flashback', 'flat', 'flatmate', 'fledgling', 'flee', 'flesh', 'flop', 'flounder', 'flow', 'fly', 'focus', 'foe', 'foil', 'follow', 'footage', 'football', 'forbidden', 'force', 'foreboding', 'foreigner', 'foremost', 'forest', 'forever', 'forge', 'form', 'former', 'formula', 'fortress', 'fortune', 'forward', 'founder', 'four', 'franchise', 'francisco', 'franco', 'frankie', 'franklin', 'fraud', 'fray', 'freak', 'freddy', 'free', 'freedom', 'frequency', 'fresh', 'freshman', 'friend', 'friendship', 'frightfully', 'fu', 'fuel', 'fugitive', 'fulfill', 'full', 'fun', 'fund', 'fundamentalist', 'funnyman', 'furious', 'fury', 'future', 'gabi', 'gaffigan', 'galactic', 'galaxy', 'gambling', 'game', 'ganesh', 'gang', 'gangster', 'garfield', 'gas', 'gasteiz', 'gay', 'gaza', 'gear', 'geek', 'general', 'genius', 'genocide', 'george', 'german', 'germany', 'get', 'getaway', 'getting', 'ghost', 'ghostly', 'giant', 'gift', 'gifted', 'gilligan', 'ginger', 'girl', 'girlfriend', 'girls', 'give', 'glide', 'glitzy', 'global', 'globe', 'glory', 'go', 'goal', 'goalkeeper', 'goat', 'god', 'golden', 'golfer', 'gonzo', 'good', 'goon', 'gordon', 'gorgeous', 'gorilla', 'gory', 'government', 'grad', 'grade', 'graduate', 'grand', 'grandchild', 'grandfather', 'grandkid', 'grandmother', 'grandson', 'grant', 'grave', 'gravitate', 'great', 'greed', 'greedy', 'green', 'greenland', 'gretel', 'gridiron', 'grief', 'grieve', 'grime', 'grimm', 'grisly', 'grizzly', 'grocer', 'gromit', 'ground', 'groundbreake', 'group', 'grow', 'grubby', 'grudge', 'gruele', 'gruff', 'guadalajara', 'guardian', 'guest', 'guidance', 'guide', 'guignol', 'guitarist', 'gun', 'gunner', 'guy', 'gym', 'gymnastic', 'gynecologist', 'gypsy', 'half', 'halloween', 'hallucinogenic', 'hamburg', 'hamlet', 'hand', 'handed', 'hang', 'hansel', 'happy', 'harass', 'hardin', 'hari', 'harlem', 'harold', 'harrowing', 'harry', 'harvard', 'harvey', 'hatch', 'hate', 'haunt', 'haunted', 'havoc', 'head', 'headline', 'headstrong', 'heal', 'healing', 'health', 'healthy', 'hear', 'heart', 'heartbroken', 'hedy', 'heffron', 'heineken', 'heinous', 'heist', 'helen', 'helios', 'help', 'herd', 'hero', 'heroic', 'heroin', 'heroine', 'herzog', 'hesitate', 'hiccup', 'hidden', 'hide', 'hiding', 'hierarchy', 'high', 'hijack', 'hijinks', 'hilarious', 'hilariously', 'hill', 'hindi', 'hip', 'hire', 'hiroshima', 'historic', 'history', 'hit', 'hitch', 'hiv', 'hiyori', 'hockey', 'hold', 'hole', 'holiday', 'holly', 'hollywood', 'holmes', 'home', 'homeless', 'homemaker', 'homeowner', 'homesteader', 'hometown', 'honest', 'honey', 'hong', 'honor', 'hook', 'hookup', 'hop', 'hope', 'hopping', 'horn', 'horrible', 'horrific', 'horror', 'horse', 'host', 'hostile', 'hot', 'hotel', 'hour', 'house', 'housewife', 'housing', 'howleen', 'hubris', 'hughes', 'hughley', 'human', 'humanity', 'humanoid', 'humble', 'humor', 'humorous', 'hundred', 'hunger', 'hunt', 'hunter', 'hunting', 'hurricane', 'husband', 'hustler', 'hyderabad', 'hydra', 'hypocrisy', 'hüseyin', 'ice', 'icon', 'iconic', 'ideal', 'idealistic', 'identical', 'identity', 'ideology', 'idol', 'idyllic', 'ig', 'ignore', 'ii', 'illegal', 'illicit', 'imaginative', 'immature', 'immigration', 'immortality', 'immune', 'impact', 'imperil', 'impersonate', 'impersonation', 'important', 'imposter', 'impostor', 'impoverished', 'impression', 'imprison', 'improve', 'impulsive', 'impulsively', 'inadvertently', 'incarcerate', 'incident', 'inclined', 'incorrect', 'increasingly', 'incredible', 'incurable', 'indelibly', 'independence', 'india', 'indian', 'indiana', 'indigenous', 'individually', 'indonesia', 'indonesian', 'industrial', 'industrialist', 'inexplicably', 'infant', 'infatuate', 'infiltrate', 'influence', 'influential', 'information', 'ingenious', 'ingenuity', 'inhabit', 'inheritance', 'initiative', 'injure', 'injury', 'injustice', 'inmate', 'inn', 'innocence', 'innocent', 'innovative', 'inside', 'insider', 'insight', 'insightful', 'insist', 'insomniac', 'inspire', 'installment', 'instant', 'instead', 'institution', 'instructor', 'intact', 'intelligence', 'intend', 'intense', 'interactive', 'interest', 'internal', 'international', 'internet', 'interpretation', 'interracial', 'intersect', 'interview', 'interwoven', 'intimacy', 'intimate', 'intimidate', 'intrepid', 'intrigue', 'introduce', 'introspective', 'intruder', 'invader', 'invasion', 'invention', 'inventor', 'investigate', 'investigation', 'invincible', 'invitation', 'invite', 'involve', 'involvement', 'ip', 'iqbal', 'iranian', 'iraq', 'iron', 'irresistible', 'ishmael', 'island', 'isoken', 'isolated', 'issue', 'italian', 'italy', 'iv', 'ivory', 'jack', 'jacob', 'jakarta', 'james', 'jamie', 'japan', 'japanese', 'jazz', 'jealousy', 'jefferies', 'jefferson', 'jeopardize', 'jeopardy', 'jeremiah', 'jerusalem', 'jessica', 'jewelry', 'jewish', 'jews', 'jim', 'job', 'jock', 'jockey', 'johan', 'john', 'join', 'joke', 'jon', 'jonas', 'jones', 'jordan', 'jorge', 'joseph', 'journal', 'journalism', 'journalist', 'journey', 'judd', 'jump', 'jumper', 'jungle', 'juni', 'justice', 'justin', 'jutanugarn', 'karina', 'karnataka', 'kashmir', 'kat', 'kath', 'katherine', 'keen', 'keep', 'kel', 'kennedy', 'kenney', 'kerala', 'kevyn', 'key', 'kgb', 'khan', 'kid', 'kidnap', 'kidnapper', 'kidnapping', 'kiki', 'kill', 'killer', 'killmonger', 'kim', 'kimberly', 'kimmy', 'kind', 'king', 'kingdom', 'kingpin', 'kitten', 'klaue', 'klutz', 'knife', 'knight', 'know', 'koko', 'kondabolu', 'kong', 'korea', 'krumpe', 'kublai', 'kudret', 'kung', 'la', 'lab', 'laborer', 'lady', 'ladybug', 'lake', 'lamarr', 'lampoon', 'lance', 'land', 'landon', 'language', 'lapd', 'lapis', 'large', 'lark', 'las', 'last', 'late', 'later', 'lauda', 'laugh', 'launch', 'laurel', 'lava', 'lavish', 'law', 'lawless', 'lawman', 'lawyer', 'lazuli', 'lead', 'leader', 'leaf', 'league', 'learn', 'leave', 'lecherous', 'lecturer', 'lee', 'leftist', 'legacy', 'legal', 'legend', 'legendary', 'length', 'lesbian', 'leslie', 'less', 'let', 'lethal', 'level', 'liam', 'lie', 'lieutenant', 'life', 'lifelike', 'lifelong', 'lifetime', 'lift', 'light', 'like', 'lillian', 'limb', 'limbo', 'lionel', 'little', 'live', 'lively', 'living', 'liz', 'local', 'location', 'lock', 'logger', 'logue', 'london', 'londoners', 'lone', 'loneliness', 'lonely', 'long', 'longstanding', 'longtime', 'look', 'loom', 'loop', 'lord', 'los', 'lose', 'loss', 'lost', 'lot', 'lottery', 'loud', 'love', 'lover', 'loving', 'low', 'lowlife', 'loyal', 'loyalty', 'lpga', 'luccas', 'lucha', 'luciana', 'luciano', 'luck', 'lucknow', 'lucky', 'lucrative', 'lur', 'lure', 'lurk', 'lush', 'lyla', 'lyle', 'lyrical', 'mac', 'machete', 'machine', 'mad', 'madam', 'madness', 'madrid', 'mafia', 'magic', 'magical', 'magician', 'magnate', 'magnus', 'magoo', 'mail', 'maine', 'majestic', 'major', 'make', 'makeup', 'making', 'male', 'malicious', 'man', 'manager', 'maneuver', 'mango', 'manner', 'manny', 'manolo', 'mansion', 'manuela', 'manufacturer', 'maratha', 'mare', 'maricela', 'marine', 'marinette', 'mark', 'market', 'marlon', 'marriage', 'married', 'marry', 'martial', 'martin', 'mask', 'mass', 'massacre', 'massage', 'massive', 'master', 'match', 'material', 'maternal', 'math', 'matriarch', 'matter', 'mattie', 'mature', 'maverick', 'mavis', 'may', 'maya', 'mayan', 'mean', 'meaning', 'meanwhile', 'meat', 'mechanic', 'med', 'medicine', 'medina', 'medium', 'meek', 'meet', 'megan', 'mellera', 'mello', 'member', 'memory', 'men', 'menace', 'mend', 'mental', 'mentor', 'mercurial', 'mere', 'merge', 'message', 'meticulous', 'mettle', 'mexican', 'mexico', 'michael', 'michelin', 'michelson', 'mid1960', 'middle', 'might', 'migrant', 'mike', 'mildred', 'milea', 'miles', 'militaristic', 'military', 'militia', 'mill', 'millennial', 'million', 'millionaire', 'mimic', 'mind', 'minded'

In [ ]:
# I'm curious about their sizes...
print(f"Cast Vocabulary Size: {len(cast_vocabulary)}")
print(f"Description Vocabulary Size: {len(desc_vocabulary)}")
print(f"Listed_in Vocabulary Size: {len(listed_in_vocabulary)}")

# the number of unique vocab words looks right...

Cast Vocabulary Size: 3848
Description Vocabulary Size: 3332
Listed_in Vocabulary Size: 20

In [ ]:
print("Listed_In vocab: ", listed_in_vocabulary)
# I want to remove 'movies' from the vocabulary and the listed_in options... but I'm not sure whether it's worth it
# How many movies have 'movie' in it?
print(listed_in)
print(listed_in.count(['movies']))

# ok so there are rows with just 'movies' in their 'listed_in' so I just want to keep them for now... for peace of mind...

Listed_In vocab:  ['action & adventure', 'anime features', 'children & family movies', 'classic movies', 'comedies', 'cult movies', 'documentaries', 'dramas', 'faith & spirituality', 'horror movies', 'independent movies', 'international movies', 'lgbtq movies', 'movies', 'music & musicals', 'romantic movies', 'sci-fi & fantasy', 'sports movies', 'stand-up comedy', 'thrillers']

## Encoding the "Big 3" ('cast', 'listed_in', and 'description)
Reasoning: Naive Bayes uses numbers to predict, so we need to have numerical representations for each of these features...

In [ ]:
# I want to put the lists into df
df['cast'] = cast
df['description'] = description
df['listed_in'] = listed_in
df.sample(5)

,show_id,director,cast,country,release_year,rating,duration,listed_in,description,date_added_month,date_added_day,date_added_year,date_added_month_cos,date_added_month_sin,date_added_day_cos,date_added_day_sin
333,333,38,"[sanjay dutt, arjun kapoor, kriti sanon, zeena...",34,2019,4,171.0,"[dramas, international movies, romantic movies]","[18th, century, india, maratha, commander, lea...",2,14,2020,0.75,0.933013,0.010926,0.603956
460,460,124,[rachael stirling],78,2017,2,44.0,[documentaries],"[jessica, diana, sister, separate, year, age, ...",6,1,2017,0.00,0.500000,0.989074,0.603956
97,97,222,"[chiwetel ejiofor, martin sheen, danny glover,...",89,2018,4,105.0,"[dramas, faith & spirituality, independent mov...","[crisis, faith, set, renowned, fundamentalist,...",4,13,2018,0.25,0.933013,0.043227,0.703368
236,236,254,"[ezgi mola, murat yıldırım, gülenay kalkan, eb...",75,2015,5,104.0,"[comedies, international movies, romantic movies]","[30, year, old, never, take, traditional, path...",4,23,2021,0.25,0.933013,0.552264,0.002739
256,256,25,"[vicky kaushal, angira dhar, alankrita sahai, ...",34,2018,4,133.0,"[comedies, international movies, romantic movies]","[individually, bank, employee, sanjay, karina,...",2,14,2018,0.75,0.933013,0.010926,0.603956

About Encoding:

'Cast' and 'Listed_in' are categorical features (because they categorize movies) but 'description' is a text feature (they describe, but not categorize movies).

So, for categorical variables, we can do One-Hot Encoding. We don't want to do label encoding because label encoding can imply an order or 'ranking' nature to the values, which is untrue.

For 'description', we need to do either CountVectorizer (which values the words by frequency), or TF-IDF (which puts values on the words by relevance. This is good for making sure keywords like 'thriller' in the description mean more than 'movie' or 'person' showing up in the description)

In [ ]:
# ONE HOT ENCODING FOR CAST AND LISTED_IN
# https://www.geeksforgeeks.org/one-hot-encoding-from-a-pandas-column-containing-a-list/

import pandas as pd
import numpy as np

# (1) flatten lists and get unique categories
# flatten cast
all_cast_members = list([person for sublist in df['cast'] for person in sublist])
all_genres = list([genre for sublist in df['listed_in'] for genre in sublist])

# (2) create one hot encoded columns
# One-hot encoding for 'cast'
df_cast_encoded = pd.DataFrame(
    [[1 if person in cast else 0 for person in all_cast_members] for cast in df['cast']],
    columns=all_cast_members
)

# One-hot encoding for 'listed_in'
df_listed_in_encoded = pd.DataFrame(
    [[1 if genre in listed else 0 for genre in all_genres] for listed in df['listed_in']],
    columns=all_genres
)

In [ ]:
# # bring it back to original DataFrame
# df_combined = pd.concat([df, df_cast_encoded, df_listed_in_encoded], axis=1)

# # drop the original 'cast' and 'listed_in' columns if you don't need them anymore
# df_combined = df_combined.drop(columns=['cast', 'listed_in'])

# df_combined.sample(5)

In [ ]:
df_cast_encoded.sample(5)

,maia morgenstern,olimpia melinte,crina semciuc,flavia hojda,maria dinulescu,alex călin,vlad logigan,sali levent,silvia busuioc,mihaela mihut,...,jonah bobo,josh hutcherson,dax shepard,kristen stewart,tim robbins,frank oz,john alexander,derek mears,douglas tait,joe bucaro iii
149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df['description'] = df['description'].apply(lambda x: ' '.join(x))
df['description'].sample(3)

429    matriarch bent lavish 51st birthday party fami...
36     monster go mouse nap spree new york fievel fri...
421    grow post apocalyptic 2018 john connor must le...
Name: description, dtype: object

In [ ]:
# TF-IDF FOR DESCRIPTION
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
desc_encoded = vectorizer.fit_transform(df['description'])

In [ ]:
# Convert sparse matrix to dense array and create DataFrame
desc_encoded_dense = desc_encoded.toarray()  # we want to convert it to dense array
df_desc_encoded = pd.DataFrame(desc_encoded_dense, columns=vectorizer.get_feature_names_out())

# concatenate with other features
df_combined = pd.concat([df_cast_encoded, df_listed_in_encoded, df_desc_encoded], axis=1)

In [ ]:
df_combined.sample(5)

,maia morgenstern,olimpia melinte,crina semciuc,flavia hojda,maria dinulescu,alex călin,vlad logigan,sali levent,silvia busuioc,mihaela mihut,...,young,youth,youtube,yuletide,zack,zany,zathura,zealot,zombie,şeref
476,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
137,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
312,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df = pd.concat([df, df_combined], axis=1)
df.sample(5)

,show_id,director,cast,country,release_year,rating,duration,listed_in,description,date_added_month,...,young,youth,youtube,yuletide,zack,zany,zathura,zealot,zombie,şeref
425,425,155,"[sam ashe arnold, jakob davies, dalila bela, r...",10,2016,0,88.0,[children & family movies],find peculiar key three smart adventurous kid ...,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
287,287,449,"[julia roberts, lily collins, armie hammer, na...",93,2012,2,106.0,"[children & family movies, comedies]",remake classic grimm tale follow fair skinned ...,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
135,135,309,[david a. arnold],89,2020,5,61.0,[stand-up comedy],finally comfortable skin season comic david ar...,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
382,382,480,"[david arquette, neve campbell, courteney cox,...",89,2000,6,117.0,[horror movies],installment tongue cheek horror franchise find...,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76,76,193,"[brad paisley, nate bargatze, john heffron, jo...",89,2017,5,63.0,"[music & musicals, stand-up comedy]",country music star brad paisley host night mus...,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

No way I have over 15k columns just from one-hot encoding cast members and descriptions alone 😢

In [ ]:
# Ok I need to drop the original text-related columns of the Big 3 before passing it into a Naive Bayes model
df = df.drop(columns=['cast', 'listed_in', 'description'])

In [ ]:
df.sample(5)

,show_id,director,country,release_year,rating,duration,date_added_month,date_added_day,date_added_year,date_added_month_cos,...,young,youth,youtube,yuletide,zack,zany,zathura,zealot,zombie,şeref
412,412,477,10,2014,7,112.0,9,24,2017,0.500000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
435,435,427,3,2015,5,95.0,4,26,2017,0.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
321,321,272,3,2018,6,120.0,1,3,2019,0.933013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
508,508,470,34,2019,4,116.0,8,2,2019,0.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
531,531,99,68,2018,5,130.0,2,15,2019,0.750000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Remove duplicate cast name features (I found this out when doing Milestone 3 work)
# solution found on https://stackoverflow.com/questions/14984119/python-pandas-remove-duplicate-columns
df = df.loc[:,~df.columns.duplicated()].copy()

## Split Data

In [ ]:
# split data (70/30)
from sklearn.model_selection import train_test_split

# define X and y
X = df.drop(columns=['rating']) # everything is 'X' except the rating
y = df['rating']

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Naive Bayes Model

In [ ]:
# Filter rows with any negative values
negative_rows = df[(df < 0).any(axis=1)]

print(negative_rows)

Empty DataFrame
Columns: [show_id, director, country, release_year, rating, duration, date_added_month, date_added_day, date_added_year, date_added_month_cos, date_added_month_sin, date_added_day_cos, date_added_day_sin, maia morgenstern, olimpia melinte, crina semciuc, flavia hojda, maria dinulescu, alex călin, vlad logigan, sali levent, silvia busuioc, mihaela mihut, samuel l. jackson, john heard, kelly rowan, clifton collins jr., tony plana, nicole brydon bloom, giles matthey, taylor nichols, alan blumenfeld, celeste sully, susan davis, clayton hoff, earnestine phillips, ramzy bedia, éric judor, benoît magimel, kristin scott thomas, élodie bouchez, édouard baer, fred testot, omar sy, jacob elordi, adan canto, radha mitchell, tiera skovbye, kari matchett, tahmoh penikett, anders danielsen lie, jon øigarden, jonas strand gravli, ola g. furuseth, maria bock, thorbjørn harr, jaden smith, elle fanning, naomi watts, susan sarandon, tate donovan, linda emond, jordan carlos, sam trammell, maria dizzia, tessa albertson, massimo ghini, ricky memphis, martina stella, ralph palka, biagio izzo, riccardo rossi, paola minaccioni, anton yelchin, bérénice marlohe, olivia thirlby, lambert wilson, frank langella, glenn close, adam sandler, drew barrymore, rob schneider, sean astin, lusia strus, dan aykroyd, amy hill, allen covert, blake clark, maya rudolph, ehan bhat, edilsy vargas, manisha koirala, lisa ray, tenzin dalha, warina hussain, ranjit barot, neel tyagi, rahul ram, diwakar pundir, mila kunis, ...]
Index: []

[0 rows x 7197 columns]

In [ ]:
# https://www.datacamp.com/tutorial/naive-bayes-scikit-learn
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB() # init NB model

# fit the model
nb.fit(X_train, y_train)

# make prediction about the rating
y_predict = nb.predict(X_test)

# taking an example
# print("Actual val: ", y_test[0]) # wait this didn't work
# print("Predicted : ", y_predict[0])

## Model Evaluation

remember:
- false positive = you think it's positive, but it isn't

- false negative = you think it's negative, but it isn't

Reminder:
- Precision = TP / (TP+FP)
- Recall = TP / (TP+FN)
- F1 = 2*((Precision x Recall) / (Precision+Recall))
- Support = actual num of smaples per category

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# find the model's accuracy
accuracy = accuracy_score(y_test, y_predict)
print('Accuracy: ', accuracy)

# precision
print('Precision', precision_score(y_test, y_predict, average='weighted'))

# recall
print('Recall', recall_score(y_test, y_predict, average='weighted'))

# f1
print('F1', f1_score(y_test, y_predict, average='weighted'))

# support
# print('Support', support_score(y_test, y_predict, average='weighted'))
print("\n",classification_report(y_test, y_predict))

Accuracy:  0.29906542056074764
Precision 0.21170449488206497
Recall 0.29906542056074764
F1 0.14948057856723096

               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00        19
           3       0.00      0.00      0.00         9
           4       0.50      0.04      0.07        27
           5       0.30      1.00      0.46        31
           6       0.00      0.00      0.00        17

    accuracy                           0.30       107
   macro avg       0.11      0.15      0.07       107
weighted avg       0.21      0.30      0.15       107

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# Using a confusion matrix to visualize the results, especially what are the True Positives/True Negatives
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics

# referring to zybooks' classification metrics unit
# calculate the confusion matrix for each model
print("Naive Bayes model \n", metrics.confusion_matrix(y_test, y_predict))

Naive Bayes model
 [[ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0 19  0]
 [ 0  0  0  0  0  9  0]
 [ 0  0  0  0  1 26  0]
 [ 0  0  0  0  0 31  0]
 [ 0  0  0  0  1 16  0]]

Interpreting the confusion matrix: Rows represent the actual classes (true labels), columns are the predicted classes. So, cm[n][n] represents a correct and true prediction.

In [ ]:
df['rating'].unique()

array([5, 6, 3, 4, 0, 2, 1, 8, 7])

Recall that this is the code for encoding the ratings:

```
# Encoding rating
rating_mapping = {
    'TV-Y': 0,
    'G' : 1,
    'PG' : 2,
    'PG-13': 3,
    'TV-14': 4,
    'TV-MA': 5,
    'R': 6,
    'NC-17': 7,
    'UR' : 8
}
df['rating'] = df['rating'].map(rating_mapping)
```
Since there are 8/9 of the ratings that showed up, the matrix is 8x8

EDIT: Sometimes the confusion matrix changes dimensions because I randomly deleted a LOT of rows, so it would not be a surprise to know that a lot of the ratings in one rating category disappeared.

## Reflections

- Reflection: this model has a very low accuracy (42.27%) and a poor F1 score.
  - I've been referring to https://encord.com/blog/f1-score-in-machine-learning/#:~:text=How%20do%20you%20interpret%20the,to%20have%20a%20poor%20performance. to figure out how to interpret F1

- Honestly, I'm not surprised. There's a lot that goes into a movie to determine its rating. For example, in this dataset, we don't consider profanity, non-family-friendly content, and thematic elements. But I also really wonder what could better predict the movie ratings... Am I using too few models? Should I have gone for a Random Forest situation where I use multiple learning models and combine them? Maybe if I had a little more time, that would be something I can explore...

# Post-Milestone 2
This includes all things that I should have completed in Milestone 2 but didn't get to do (or forgot to do) back then.

In [ ]:
# First, I wonder if I overfitted or underfitted the model
# I will check by testing the model against the training data

y_predict_ontraining = nb.predict(X_train)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# find the model's accuracy
accuracy = accuracy_score(y_test, y_predict)
print('Accuracy: ', accuracy)

# precision
print('Precision', precision_score(y_test, y_predict, average='weighted'))

# recall
print('Recall', recall_score(y_test, y_predict, average='weighted'))

# f1
print('F1', f1_score(y_test, y_predict, average='weighted'))

# support
# print('Support', support_score(y_test, y_predict, average='weighted'))
print("\n",classification_report(y_test, y_predict))

Accuracy:  0.29906542056074764
Precision 0.21170449488206497
Recall 0.29906542056074764
F1 0.14948057856723096

               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00        19
           3       0.00      0.00      0.00         9
           4       0.50      0.04      0.07        27
           5       0.30      1.00      0.46        31
           6       0.00      0.00      0.00        17

    accuracy                           0.30       107
   macro avg       0.11      0.15      0.07       107
weighted avg       0.21      0.30      0.15       107

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

So, it looks like I actually ***underfitted*** the model, because it's doing poorly in both testing and training data in terms of accuracy. They're both about 43%. I wonder if it's because I encoded the words in description incorrectly.

Edit: I implemented lemmatization before TF-IDF encoding for description and it increased accuracies from 43% to 45%. I think it's interesting because I wished it could have gone higher, but at the same time, I understand that this is a complex dataset.

## Cross Validating the Naive Bayes Model

I will choose another model to run and test the data on. My best options at the moment are:
- Gradient Boosting
  - High accuracy
  - effective at handling noisy datasets
  - Computationally intensive, prone to overfitting
- Random Forest
  - multiple decision trees
  - allows bagging and ensemble learning
  - reduces overfitting compared to a single dec tree
  - slower to train, may be less interpretable
  - requires careful fine tuning
- NN Models

In [ ]:
y.unique()

array([5, 6, 3, 4, 0, 2, 1, 8, 7])

In [ ]:
df.sample(5)

,show_id,director,country,release_year,rating,duration,date_added_month,date_added_day,date_added_year,date_added_month_cos,...,young,youth,youtube,yuletide,zack,zany,zathura,zealot,zombie,şeref
406,406,303,89,2006,4,94.0,9,15,2019,0.500000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
451,451,468,89,2020,3,110.0,8,10,2020,0.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
351,351,46,89,1988,6,134.0,3,1,2021,0.500000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119,119,134,38,2019,4,118.0,5,14,2020,0.066987,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
346,346,408,34,2019,4,132.0,4,29,2020,0.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# pip install dask[dataframe]

In [ ]:
# export df to csv
df.to_csv('test.csv', index=False)

In [ ]:
df.sample()

,show_id,director,country,release_year,rating,duration,date_added_month,date_added_day,date_added_year,date_added_month_cos,...,young,youth,youtube,yuletide,zack,zany,zathura,zealot,zombie,şeref
524,524,64,89,2020,5,88.0,4,4,2021,0.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
pick_cols = [col for col in df.columns if re.search(r'[^a-zA-Z0-9_]', col)]
print("Problematic Columns:", pick_cols)

Problematic Columns: ['maia morgenstern', 'olimpia melinte', 'crina semciuc', 'flavia hojda', 'maria dinulescu', 'alex călin', 'vlad logigan', 'sali levent', 'silvia busuioc', 'mihaela mihut', 'samuel l. jackson', 'john heard', 'kelly rowan', 'clifton collins jr.', 'tony plana', 'nicole brydon bloom', 'giles matthey', 'taylor nichols', 'alan blumenfeld', 'celeste sully', 'susan davis', 'clayton hoff', 'earnestine phillips', 'ramzy bedia', 'éric judor', 'benoît magimel', 'kristin scott thomas', 'élodie bouchez', 'édouard baer', 'fred testot', 'omar sy', 'jacob elordi', 'adan canto', 'radha mitchell', 'tiera skovbye', 'kari matchett', 'tahmoh penikett', 'anders danielsen lie', 'jon øigarden', 'jonas strand gravli', 'ola g. furuseth', 'maria bock', 'thorbjørn harr', 'jaden smith', 'elle fanning', 'naomi watts', 'susan sarandon', 'tate donovan', 'linda emond', 'jordan carlos', 'sam trammell', 'maria dizzia', 'tessa albertson', 'massimo ghini', 'ricky memphis', 'martina stella', 'ralph palka', 'biagio izzo', 'riccardo rossi', 'paola minaccioni', 'anton yelchin', 'bérénice marlohe', 'olivia thirlby', 'lambert wilson', 'frank langella', 'glenn close', 'adam sandler', 'drew barrymore', 'rob schneider', 'sean astin', 'lusia strus', 'dan aykroyd', 'amy hill', 'allen covert', 'blake clark', 'maya rudolph', 'ehan bhat', 'edilsy vargas', 'manisha koirala', 'lisa ray', 'tenzin dalha', 'warina hussain', 'ranjit barot', 'neel tyagi', 'rahul ram', 'diwakar pundir', 'mila kunis', 'kristen bell', 'kathryn hahn', 'christine baranski', 'jay hernandez', 'cheryl hines', 'peter gallagher', 'justin hartley', 'cristina vee', 'bryce papenbrook', 'keith silverstein', 'mela lee', 'max mittelman', 'carrie keranen', 'stephanie sheh', 'selah victor', 'ben diskin', 'erin fitzgerald', 'grant george', 'laura marano', 'gregg sulkin', 'isabella gomez', 'johannah newmarch', 'lillian doucet-roche', 'chanelle peloso', 'barclay hope', 'garfield wilson', 'will forte', 'domhnall gleeson', 'martin mull', 'joel mchale', 'matt lucas', 'thomas lennon', 'seth green', 'jackie tohn', 'natasha lyonne', 'emmy rossum', 'elvy yost', 'matt walsh', 'john gemberling', 'rick glassman', 'camille guaty', 'julie walters', 'laura flannery', 'james cavlo', 'harry hains', 'clemmie dugdale', 'dendrie taylor', 'bryan chesters', 'jennifer dorogi', 'adam lazarre-white', 'nikita ramsey', 'oscar isaac', 'jessica chastain', 'david oyelowo', 'albert brooks', 'elyes gabel', 'catalina sandino moreno', 'christopher abbott', 'peter gerety', 'alessandro nivola', 'liev schreiber', 'jeanne tripplehorn', 'joelle carter', 'louise fletcher', 'katie carr', 'renée soutendijk', 'huub stapel', 'michael pas', 'carmen machi', 'pepón nieto', 'kiti mánver', 'jon kortajarena', 'jimmy castro', 'ricardo nkosi', 'montse pla', 'malcolm treviño-sitté', 'pepa charro', 'esperanza elipe', 'mariana cordero', 'txema blasco', 'miyu irino', 'saori hayami', 'aoi yuki', 'kensho ono', 'yuki kaneko', 'yui ishikawa', 'megumi han', 'toshiyuki toyonaga', 'mayu matsuoka', 'ken olin', 'jill eikenberry', 'maureen mueller', 'gregg henry', 'nicholas pryor', 'noble willingham', 'peter michael goetz', 'ron perlman', 'theodore bikel', 'olivia burnette', 'bill allen', 'brad pitt', 'mandy moore', 'shane west', 'peter coyote', 'daryl hannah', 'lauren german', 'clayne crawford', 'al thompson', 'isabella acres', 'drake bell', 'emilio estevez', 'nolan gould', 'matthew lillard', 'ray liotta', 'jane lynch', 'ariel winter', 'patricio castillo', 'sergio bustamante', 'alejandro suárez', 'luz maría jerez', 'bob isaacs', 'tere monroy', 'sarah jeffery', 'simon paul mutuyimana', 'denis theriault', 'jeremiah sparks', 'steven love', 'cara ricketts', 'jim codrington', 'shamier anderson', 'stephan james', 'lanette ware', 'hugh thompson', 'p. samuthirakani', 'madhumathi padmanathan', 'akalyadevi b.', 's i neelambari', 'josephine langford', 'hero fiennes tiffin', 'selma blair', 'inanna sarkis', 'shane paul mcghie', 'pia mia', 'khadijha red thunder', 'dylan arnold', 'samuel larsen', 'jennifer beals', 'amitabh bachchan', 'mithun chakraborty', 'danny denzongpa', 'alok nath', 'rohini hattangadi', 'tinnu anand', 'vikram gokhale', 'archana puran singh', 'martin l. washington jr.', 'maya washington', 'matt dallas', "christopher o'shea", 'jason scott lee', 'margaret cho', 'kevin daniels', 'john fleck', 'nia peeples', 'adam tomei', 'youssef chahine', 'hussein fahmy', 'amr abdel-geleel', 'taheya cariocca', 'hesham selim', 'huda sultan', 'ragaa hussein', 'jeffrey wright', 'ashton sanders', 'regina taylor', 'yahya abdul-mateen ii', 'isaiah john', 'kelly jenrette', 'shakira ja-nai paye', 'johnny massaro', 'bianca comparato', 'regina braga', 'maria laura nogueira', 'victor mendes', 'thiago amaral', 'rafael primot', 'eduardo mossri', 'rita batata', 'larissa ferrara', 'javicia leslie', 'jordan calloway', 'richard lawson', 'yvette nicole brown', 'michelle mitchenor', 'amber chardae robinson', 'jasmin brown', 'kevin spacey', 'annette bening', 'thora birch', 'wes bentley', 'mena suvari', 'chris cooper', 'allison janney', 'scott bakula', 'sam robards', 'hayden christensen', 'adrien brody', 'jordana brewster', 'tory kittles', 'luis da silva jr.', 'lance e. nichols', 'joe chrest', 'thomas dekker', 'lacey chabert', 'jane singer', 'nehemiah persoff', 'susan boyd', 'robert hays', 'pat musick', 'dom deluise', 'candi milo', 'jeff bennett', 'oona chaplin', 'natalia tena', 'david verdaguer', 'geraldine chaplin', 'andré chiang', 'anjelah johnson-reyes', 'sanjay mishra', 'seema pahwa', 'rajat kapoor', 'taranjit kaur', 'maya sarao', 'chandrachoor rai', 'namit das', 'brijendra kala', 'alka chawla', 'manu rishi chadha', 'bailee madison', 'robert capron', 'rachel resheff', 'mavrick moreno', 'whitney goin', 'gary weeks', 'juliana harkavy', 'kevin b. mcglynn', 'jamison stern', 'mia matthews', 'bianca matthews', 'mohamed henedi', 'bassem samra', 'dorra zarrouk', 'lotfy labib', 'dan stevens', 'lucy boynton', 'michael sheen', 'mark lewis jones', 'bill milner', 'kristine froseth', 'paul higgins', 'richard elfyn', 'elen rhys', "ross o'hennessy", 'ahmed eid', 'ayten amer', 'ahmed fouad selim', 'mohsen mansour', 'priyanka bose', 'vaibhav raj gupta', 'santosh juvekar', 'anangsha biswas', 'ankit raaj', 'kashmira irani', 'kailash waghmare', 'vipin sharma', 'shah rukh khan', 'kareena kapoor', 'rahul dev', 'hrishitaa bhatt', 'gerson da cunha', 'subhashini ali', 'umesh mehra', 'sooraj balaji', 'roy marsden', 'sam gittins', 'grant masters', 'neerja naik', 'abigail cruttenden', 'kris saddler', 'holly weston', 'david bradley', 'gina rodriguez', 'ariana greenblatt', 'frances fisher', 'jennifer jason leigh', 'barry pepper', 'finn jones', 'lucius hoyos', 'gil bellows', 'jack cutmore-scott', 'lili simmons', 'brandon scott', 'chase williamson', 'noureen dewulf', 'seth morris', 'christine donlon', 'trent haaga', 'kahyun kim', 'cynthia rose hall', 'zedrick restauro', 'eric podnar', 'theeradej wongpuapan', 'sirin horwang', 'ungsumalynn sirapatsakmetha', 'panissara phimpru', 'taksaorn paksukcharern', 'charlie trairat', 'kazuki yano', 'kelly sheridan', 'kazumi evans', 'claire corlett', 'ashlyn drummond', 'alex kelly', 'tabitha st. germain', 'shannon chan-kent', 'józef pawłowski', 'zofia domalik', 'szymon bobrowski', 'bartłomiej topa', 'janusz chabior', 'rafał zawierucha', 'antoni pawlicki', 'cezary łukaszewicz', 'danuta stenka', 'jan frycz', 'damian majewski', 'deep joshi', 'jasmine kaur', 'mohit bhaskar', 'vijay s. kumar', 'prince kanwaljit singh', 'tarlochan singh', 'harsh sethi', 'luis gerardo méndez', 'brontis jodorowsky', 'joonas saartamo', 'laura birn', 'ilkka koivula', 'ville virtanen', 'raúl villegas', 'miriam balderas', 'ximena guzmán', 'ashleigh ball', 'lili beaudoin', 'charles demers', 'rebecca husain', 'erin mathews', 'jerry seinfeld', 'renée zellweger', 'matthew broderick', 'patrick warburton', 'john goodman', 'chris rock', 'kathy bates', 'barry levinson', 'larry king', 'tony mccoy', 'bert kreischer', 'gerald anderson', 'julia barretto', 'yayo aguila', 'christian vazquez', 'cezmi baskın', 'özgü namal', 'umut kurt', 'nazmi kırık', 'bahri beyat', 'meral okay', 'dilber ay', 'şahin irmak', 'oktay kaynarca', 'burak tamdoğan', 'sunny kaushal', 'rukshar dhillon', 'shriya pilgaonkar', 'parmeet sethi', 'samir soni', 'chaitanya sharma', 'sheeba chaddha', 'akarsh khurana', 'imran rasheed', 'mittal chouhan', 'trimala adhikari', 'bhushan vikas', 'ravi goswami', 'raghav dutt', 'kumkum chouhan', 'rohan mobarsa', 'akshay kumar', 'vidya balan', 'ameesha patel', 'shiney ahuja', 'paresh rawal', 'rajpal yadav', 'manoj joshi', 'rasika joshi', 'ajay devgn', 'urmila matondkar', 'nana patekar', 'fardeen khan', 'victor banerjee', 'seema biswas', 'jules wojciechowski', 'roger craig smith', 'david lodge', 'lindsey alena', 'sandy fox', 'joey lotsko', 'sandra bullock', 'trevante rhodes', 'john malkovich', 'sarah paulson', 'bd wong', 'jacki weaver', 'rosa salazar', 'danielle macdonald', 'lil rel howery', 'tom hollander', 'mary joy apostol', 'arnold reyes', 'ku aquino', 'john arcilla', 'dido dela paz', 'elora espano', 'ronnie quizon', 'rolando t. inocencio', 'suzette ranillo', 'angelica c. ferro', 'raúl arévalo', 'candela peña', 'paulina garcía', 'claude musungayi', 'babou cham', 'lidia nené', 'melina matthews', 'emilio buale', 'mulie jarju', 'fenda drame', 'dairon tallon', 'teresita evuy', 'olivier bony', 'benjamin dickey', 'alia shawkat', 'josh hamilton', 'charlie sexton', 'sam rockwell', 'wyatt russell', 'steve zahn', 'kris kristofferson', 'richard linklater', 'david kallaway', 'ritchie montgomery', 'oscar martínez', 'dolores fonzi', 'diego velázquez', 'paulina garcia', 'luis gnecco', 'malena sánchez', 'emilio vodanovich', 'norman briski', 'mark duplass', 'clu gulager', 'hedy lamarr', 'mohamed saad', 'ezzat abou aouf', 'hassan hosny', 'ahmed rateb', 'hamdi el sakhawy', 'safaa el-toukhy', 'wendy raquel robinson', 'ross fleming', 'shondrella avery', 'tammy townsend', 'omar gooding', 'tracy davis', 'veronika bozeman', 'kelly perine', 'valarie pettiford', 'brad paisley', 'nate bargatze', 'john heffron', 'jon reep', 'sarah tiana', 'mike e. winfield', 'jason momoa', 'garret dillahunt', 'jill wagner', 'stephen lang', 'sasha rosoff', 'sala baker', 'fraser aitcheson', 'teach grant', 'glenn ennis', 'todd scott', 'zahn mcclarnon', 'brendan fletcher', 'david attenborough', 'johan rockström', 'paul walker', 'david belle', 'gouchy boy', 'catalina denis', 'ayisha issa', 'carlo rota', 'andreas apergis', 'richard zeman', 'robert maillet', 'arjun mathur', 'nidhi singh', 'manav vij', 'sheetal thakur', 'sunny hinduja', 'yogendra tikku', 'vijayant kohli', 'cem gelinoğlu', 'melis babadag', 'ege kökenli', 'müfit kayacan', 'lale başar', 'ali erkazan', 'özlem çakar', 'selen domaç', 'ferdi sancar', 'güven hokna', 'faizon love', 'kirk fox', 'tony todd', 'pearl thusi', 'cassie clare', 'fiona ramsey', 'neels clasen', 'roxy nel', 'dulquer salmaan', 'karthika muraleedharan', 'soubin shahir', 'dileesh pothan', 'john vijay', 'chandini sreedharan', 'jinu joseph', 'sujith shankar', 'alencier ley lopez', 'virginia madsen', 'xander berkeley', 'kasi lemmons', 'vanessa williams', 'dejuan guy', 'michael culkin', 'stanley desantis', 'chicco jerikho', 'pevita pearce', 'johnny depp', 'freddie highmore', 'david kelly', 'helena bonham carter', 'noah taylor', 'missi pyle', 'james fox', 'deep roy', 'christopher lee', 'adam godley', 'annasophia robb', 'julia winter', 'jordan fry', 'philip wiegratz', 'wilmer valderrama', 'demi lovato', 'nia vardalos', 'ashley tisdale', 'avril lavigne', 'g.e.m.', 'john cleese', 'chris harrison', 'dee bradley baker', 'carlos alazraqui', 'kaustav ghosh', 'jigna bhardwaj', 'rajesh kava', 'guru shambu', 'arun shekar', 'julie tejwani', 'anamaya verma', 'dick van dyke', 'sally ann howes', 'lionel jeffries', 'gert fröbe', 'anna quayle', 'benny hill', 'james robertson justice', 'robert helpmann', 'heather ripley', 'adrian hall', 'barbara windsor', 'davy kaye', 'alexander doré', 'bernard spear', 'stanley unwin', 'kostja ullmann', 'alli neumann', 'sascha alexander gersak', 'sophia thomalla', 'merlin rose', 'detlev buck', 'peter kurth', 'anika mauer', 'frederic linkemann', 'bernd hölscher', 'julian ovenden', 'gemma whelan', 'joely richardson', 'michael landes', 'sally phillips', 'patricia hodge', 'ronni ancona', 'sophie simnett', 'jade ma', 'shahid kapoor', 'om puri', 'neha dhupia', 'sunil shetty', 'shakti kapoor', 'nurgül yeşilçay', 'celile toyon uysal', 'deniz deha lostar', 'settar tanrıöğen', 'suzan aksoy', 'hüseyin avni danyal', 'jülide kural', 'ragıp savaş', 'christien anholt', 'andre braugher', 'dan futterman', 'josh lucas', 'clive owen', 'sophie ward', 'sue-ann leeds', 'laura linney', 'kate beckinsale', 'christopher walken', 'david hasselhoff', 'henry winkler', 'julie kavner', 'joseph castanon', 'jonah hill', 'jake hoffman', 'jennifer coolidge', 'jim iyke', 'joselyn dumas', 'enyinna nwigwe', 'beverly naya', 'femi adebayo', 'segun arinze', 'padita agu', 'chiwetel ejiofor', 'martin sheen', 'danny glover', 'jason segel', 'condola rashad', 'lakeith stanfield', 'stacey sargeant', 'vondie curtis-hall', 'robin weigert', 'maggie siff', 'johnathan tchaikovsky', 'ben shenkman', 'janel moloney', 'emily kinney', 'adhvik mahajan', 'prasad purandhare', 'sakshi gulati', 'zakir hussain', 'amruta subhash', 'kishore kadam', 'sumeet nijhawan', 'upyendra limaye', 'gethin anthony', 'frederikke dahl hansen', 'sebastian armesto', 'olivia grant', 'baard owe', 'mille dinesen', 'martin hestbæk', 'tamzin merchant', 'sarah butler', 'larissa albuquerque', 'kayla wallace', 'matthew maccaull', 'james dean', 'alison wandzura', 'bruce blain', 'natalie grace', 'phillip mitchell', 'don cheadle', 'matt dillon', 'jennifer esposito', 'william fichtner', 'brendan fraser', 'terrence howard', 'thandie newton', 'ryan phillippe', 'larenz tate', 'nona gaye', 'michael peña', 'ramsey nouah', 'sola sobowale', 'ireti doyle', 'ben touitou', 'francis onwochei', 'ememobong nkana', 'emem inwang', 'patrick onyeke', 'chow yun fat', 'michelle yeoh', 'zhang ziyi', 'chang chen', 'lung hsiung', 'cheng pei-pei', 'fa zeng li', 'xian gao', 'yan hai', 'de ming wang', 'noriko shinohara', 'ushio shinohara', 'd.l. hughley', 'jane turner', 'gina riley', 'glenn robbins', 'peter rowsthorn', 'magda szubanski', 'madison lawlor', 'montana manning', 'andrew pifko', 'monte markham', 'kamala jones', 'jodi carol harrison', 'seth cassell', 'ronnie clark', 'lissa danshaw', 'j.j. hawkins', 'martina schöne-radunski', 'hans-heinrich hardt', 'sebastian fräsdorf', 'claudia jacob', 'deleila piasko', 'tobias borchers', 'ruth bickelhaupt', 'daniel sosa', 'ricardo quevedo', 'nelson polanía', 'liss pereira', 'brian moreno', 'ana cristina botero', 'jairo ordóñez', 'luis alberto saavedra', 'blanca ligia franco', 'marianne schaller romero', 'shirley marulanda', 'hugh grant', 'lisa kudrow', 'kumail nanjiani', 'tracey ullman', 'samson kayo', 'leslie jones', 'diane morgan', 'cristin milioti', 'joe keery', 'panisara rikulsurakan', 'kay lertsittichai', 'supanaree sutavijitvong', 'krit jeerapattananuwong', 'warisara jitpreedasakul', 'dujdao vadhanapakorn', 'kim waddoup', 'philaiwan khamphirathat', 'wongsakorn rassamitat', 'bhumibhat thavornsiri', 'topher grace', 'genesis rodriguez', 'patricia clarkson', 'callan mulvey', 'robin thomas', 'daisy mccrackin', 'maria bello', 'frank grillo', 'cody horn', 'dustin milligan', 'megan park', 'scott mechlowicz', 'aaron yoo', 'alex goode', 'terence rosemore', 'jesse steccato', 'nour el-sherif', 'laila elwi', 'mahmoud hemeida', 'safia el-emari', 'mohamed mounir', 'khaled el nabawy', 'seif abdelrahman', 'abdalla mahmoud', 'magdi idris', 'amanda schull', 'milo ventimiglia', 'shawn ashmore', 'bridget regan', 'jonathan frakes', 'sarah constible', 'spencer drever', 'javier botet', 'kunal khemu', 'sonu sood', 'soha ali khan', 'johnny lever', 'dilip joshi', 'malay chakrabarty', 'razak khan', 'iqbaal ramadhan', 'vanesha prescilla', 'ira wibowo', 'bucek depp', 'happy salma', 'maudy koesnaedi', 'jerome kurnia', 'rishi kapoor', 'neetu singh', 'aditi vasudev', 'archit krishna', 'akhilendra mishra', 'natasha rastogi', 'manoj bakshi', 'supriya shukla', 'christopher masterson', 'harry van gorkum', 'rona figueroa', 'matt hickey', 'henry o', 'tom burke', 'robby benson', 'ken shorter', 'john woodnutt', 'lubomir misak', 'tom rhys harries', 'jessamine-bliss bell', 'patrick stewart', 'andré eriksen', 'richard cordery', 'martin hutson', 'turlough convery', 'delroy brown', 'noah kaye bentley', 'brennley brown', 'zach callison', 'nicolas cantu', 'skai jackson', 'marsai martin', 'andre robinson', 'grey griffin', 'mary elizabeth mcglynn', 'dilip kumar', 'amrita singh', 'ashok kumar', 'prem chopra', 'amrish puri', 'satyen kappu', 'mac mohan', 'javed khan', 'megumi ogata', 'kotono mitsuishi', 'megumi hayashibara', 'yuko miyamura', 'yuriko yamaguchi', 'fumihiko tachiki', 'motomu kiyokawa', 'koichi yamadera', 'takehito koyasu', 'hiro yuki', 'miki nagasawa', 'akira ishida', 'jakob dylan', 'ringo starr', 'michelle phillips', 'stephen stills', 'regina spektor', 'eric clapton', 'tom petty', 'jackson browne', 'norah jones', 'vinod mehra', 'vinod khanna', 'madan puri', 'brahm bhardwaj', 'enissa amani', 'millie bobby brown', 'henry cavill', 'sam claflin', 'louis partridge', 'burn gorman', 'adeel akhtar', 'susan wokoma', 'frances de la tour', 'fiona shaw', 'rakesh varre', 'vamsi raj nekkanti', 'd p ghani', 'k prasanna', 'zac efron', 'lily collins', 'kaya scodelario', 'jeffrey donovan', 'angela sarafyan', 'jim parsons', 'haley joel osment', 'dylan baker', 'brian geraghty', 'demet akbağ', 'ata demirer', 'özge borak', 'salih kalyon', 'tanju tuncel', 'serra yılmaz', 'tarık ünlüoğlu', 'ayşenil şamlıoğlu', 'james ransone', 'vinessa shaw', 'ajiona alexus', 'colin ford', 'charlie dizon', 'paulo avelino', 'david a. arnold', 'benicio del toro', 'tobey maguire', 'ellen barkin', 'gary busey', 'christina ricci', 'mark harmon', 'cameron diaz', 'katherine helmond', 'michael jeter', 'craig bierko', 'lyle lovett', 'christopher meloni', 'harry dean stanton', 'tim thomerson', 'frank lammers', 'elise schaap', 'monic hendrickx', 'raymond thiry', 'maarten heijmans', 'yannick van de velde', 'norma crane', 'leonard frey', 'molly picon', 'paul mann', 'rosalind harris', 'michele marsh', 'neva small', 'paul michael glaser', 'ray lovelock', 'ali larter', 'a.j. cook', "terrence 't.c.' carson", 'jonathan cherry', 'keegan connor tracy', 'sarah carter', 'lynda boyd', 'david paetkau', 'justina machado', 'tien-chi cheng', 'tien hsiang lung', 'meng lo', 'michael chan wai-man', 'pei hsi chen', 'li wang', 'ke chu', 'dianne wiest', 'rosie perez', 'teyonah parris', 'hani furstenberg', 'bill raymond', 'rubén blades', 'bruce greenwood', 'bruce mcgill', "peter o'toole", 'andy garcia', 'nestor carbonell', 'eduardo verástegui', 'eva longoria', 'santiago cabrera', 'adrian alonso', 'mauricio kuri', 'leslie nielsen', 'walter pidgeon', 'anne francis', 'jack kelly', 'warren stevens', 'james drury', 'earl holliman', 'vince vaughn', 'reese witherspoon', 'robert duvall', 'sissy spacek', 'jon voight', 'jon favreau', 'mary steenburgen', 'dwight yoakam', 'tim mcgraw', 'kristin chenoweth', 'franco escamilla', 'matthew mcconaughey', 'gugu mbatha-raw', 'mahershala ali', 'keri russell', 'christopher berry', 'sean bridgers', 'jacob lofland', 'thomas francis murphy', 'bill tangradi', 'ali al shehhi', 'huda al ghanim', 'muhammed murshed', 'yaser alneyadi', 'khaled al-nuaimi', 'nasser al-dhahnani', 'nawal chamoun', 'iman husein', 'wade allain-marcus', 'arjun gupta', 'melina lizette', 'elsa biedermann', 'katie blake', 'santana dempsey', 'saki tsukamoto', 'nada moussa', 'mohammed tharwat', 'viraaj modgill', 'jasleen singh', 'pooja punjabi', 'amit deondi', 'ketan kava', 'zeel thakkar', 'manish bhavan', 'viswanathan sridhar', 'kristin davis', 'daphne sheldrick', 'nick trent', 'julious shivenga', 'benjamin kyalo', 'frank welker', 'vanessa marshall', 'gregg berger', 'wally wingert', 'audrey wasilewski', 'jaso

## Lightgbm Gradient Boosting

In [ ]:
# # I'm going to go with Gradient Boosting with Light GBM because I learned that Light GBM does decently well with large datasets with categorical support

# import lightgbm as light

# # initialize model
# light_model = light.LGBMClassifier(
#     objective='multiclass',
#     num_class = len(y.unique())
# )

# # fit the model
# light_model.fit(X_train, y_train)

# # make prediction
# y_predict_light = light_model.predict(X_test)

In [ ]:
# # Evaluating the lightgbm model
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# # find the model's accuracy
# accuracy = accuracy_score(y_test, y_predict)
# print('Accuracy: ', accuracy)

# # precision
# print('Precision', precision_score(y_test, y_predict, average='weighted'))

# # recall
# print('Recall', recall_score(y_test, y_predict, average='weighted'))

# # f1
# print('F1', f1_score(y_test, y_predict, average='weighted'))

# # support
# # print('Support', support_score(y_test, y_predict, average='weighted'))
# print("\n",classification_report(y_test, y_predict))

# Milestone 3

Alright so I have to preface this with saying:

I attempted to cross validate my model and do some parameter fine-tuning before working on this milestone, but I ran into a lot of roadblocks such as inserting steps and debugging functions that belong in Milestones 1 and 2; I didn't anticipate the yarn that I feel like I couldn't finish unraveling. So, I will do milestone 3 to the best of my abilities. Thank you for your patience :D

In [ ]:
df.sample(5)

,show_id,director,country,release_year,rating,duration,date_added_month,date_added_day,date_added_year,date_added_month_cos,...,young,youth,youtube,yuletide,zack,zany,zathura,zealot,zombie,şeref
279,279,100,89,2013,4,84.0,1,15,2017,0.933013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
307,307,121,89,2018,4,113.0,7,1,2019,0.066987,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162,162,327,53,2017,4,93.0,1,31,2020,0.933013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
116,116,490,24,1997,4,136.0,6,19,2020,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
215,215,57,89,2018,5,101.0,4,16,2019,0.250000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Columns: 7197 entries, show_id to şeref
dtypes: float64(3321), int32(3), int64(3873)
memory usage: 29.3 MB

## Final Model Performance Analysis

I'm going to use SHAP values and LIME to get insights about the Naive Bayes Model.

### SHAP Values

Following the tutorial here: https://www.datacamp.com/tutorial/introduction-to-shap-values-machine-learning-interpretability

In [ ]:
pip install shap

Requirement already satisfied: shap in /usr/local/lib/python3.10/dist-packages (0.46.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from shap) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from shap) (1.13.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from shap) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from shap) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.10/dist-packages (from shap) (4.66.6)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.10/dist-packages (from shap) (24.2)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.10/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from shap) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from shap) (3.1.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba->shap) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->shap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->shap) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->shap) (2024.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->shap) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->shap) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->shap) (1.16.0)

In [ ]:
import shap
shap.initjs()

In [ ]:
# explainer = shap.Explainer(nb, X_train)
# shap_values = explainer(X_test)
# the above code got some errors so I'm trying this solution:

# use a function to wrap the MultinomialNB's predict_proba() for SHAP
def model_predict_proba(X):
    return nb.predict_proba(X)

# Now pass this wrapped function to the Explainer
explainer = shap.Explainer(model_predict_proba, X_train, max_evals=((2*len(df.columns))+1))  # it needs to be higher than 2*num_features + 1
shap_values = explainer(X_test)

# NOOO THE RAM CRASHED - I went from deleting 5000 rows to 5500 rows in the start of this program for this reason... let's see if this works

Alright. I'm moving to Visual Studio

## Deployment Plan

## Ethical Considerations